namespace Games;

public sealed class UniverseInfo
{
    public long UniverseId { get; set; }
    public long RootPlaceId { get; set; }
    public long CreatorUserId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string? ThumbnailUrl { get; set; }
    public int PrivacyLevel { get; set; } = 1;
    public bool Studio_Access_To_APIs { get; set; } = false;
    public int VisitCount { get; set; } = 0;
    public int PlayingCount { get; set; } = 0;
    public DateTime? LastUpdated { get; set; }
    public DateTime? CreatedAt { get; set; }
    public int Upvotes { get; set; }
    public int Downvotes { get; set; }
}

public sealed class PlaceSettingsData
{
    public long PlaceId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public int Genre { get; set; }
    public string DeviceCompatibility { get; set; } = "[]";
    public int MaxVisitorCount { get; set; } = 8;
    public int ServerFillType { get; set; }
    public int AccessType { get; set; } = 1;
    public bool PrivateServersAllowed { get; set; }
    public bool PrivateServersFree { get; set; }
    public int PrivateServersPrice { get; set; }
    public bool PaidAccessEnabled { get; set; }
    public int PaidAccessPrice { get; set; }
    public bool IsCopyingAllowed { get; set; }
    public bool IsAllGenresAllowed { get; set; }
    public string AllowedGearTypes { get; set; } = "[]";
    public bool AllowPlaceToBeCopiedInGame { get; set; }
    public bool AllowPlaceToBeUpdatedInGame { get; set; }
    public bool CustomIcon { get; set; }
    public bool GeneratedIcon { get; set; }
    public bool PlaceCustomThumbnail { get; set; }
    public bool PlaceVideoThumbnail { get; set; }
    public bool PlaceAutoGeneratedThumbnail { get; set; }
}
