-- 0033_add_place_thumbnail_fields_to_assets.sql
-- Add thumbnail-related fields to assets table for place thumbnail management
-- Description: Adds fields to track thumbnail types and URLs for places
-- Created: 2025-01-10
--
-- Note: This migration works with 0032_create_place_thumbnails.sql and 0034_fix_place_thumbnails_constraints.sql
-- The place_thumbnails table stores multiple thumbnails with auto-incrementing IDs
-- The assets table fields below store flags and the currently selected primary thumbnail

-- Add video thumbnail URL field (stores currently selected video thumbnail URL if video is primary)
ALTER TABLE IF EXISTS assets
    ADD COLUMN IF NOT EXISTS place_thumbnail_video TEXT NULL;

-- Add autogenerated thumbnail flag
ALTER TABLE IF EXISTS assets
    ADD COLUMN IF NOT EXISTS place_autogenerated_thumbnail BOOLEAN NOT NULL DEFAULT FALSE;

-- Add video thumbnail flag (indicates if video is selected as primary thumbnail)
ALTER TABLE IF EXISTS assets
    ADD COLUMN IF NOT EXISTS place_video_thumbnail BOOLEAN NOT NULL DEFAULT FALSE;

-- Add custom thumbnail flag (indicates if custom image is selected as primary thumbnail)
ALTER TABLE IF EXISTS assets
    ADD COLUMN IF NOT EXISTS place_custom_thumbnail BOOLEAN NOT NULL DEFAULT FALSE;

-- Add generated thumbnail URL field (stores auto-generated thumbnail URL if selected as primary)
ALTER TABLE IF EXISTS assets
    ADD COLUMN IF NOT EXISTS place_generated_thumbnail_url TEXT NULL;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_assets_place_thumbnail_video 
    ON assets(place_thumbnail_video) WHERE place_thumbnail_video IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_assets_place_autogenerated_thumbnail 
    ON assets(place_autogenerated_thumbnail);

CREATE INDEX IF NOT EXISTS idx_assets_place_video_thumbnail 
    ON assets(place_video_thumbnail);

CREATE INDEX IF NOT EXISTS idx_assets_place_custom_thumbnail 
    ON assets(place_custom_thumbnail);

CREATE INDEX IF NOT EXISTS idx_assets_place_generated_thumbnail_url 
    ON assets(place_generated_thumbnail_url) WHERE place_generated_thumbnail_url IS NOT NULL;

