using System;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media.Imaging;
using Assets;
using Games;
using Control_Panel.Properties;
using Control_Panel.Functions;
using ControlPanel.Functions;
using System.Text.Json;
using Thumbnails;
using Common;
using Webserver.Common;
using Microsoft.Win32;

namespace Control_Panel
{
    public class DevProductDisplayItem
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    }

    public class ThumbnailItem
    {
        public long Id { get; set; }
        public BitmapImage ImageSource { get; set; }
    }

    public partial class PlaceEditWindow : Window
    {
        private ObservableCollection<ThumbnailItem> thumbnailItems = new ObservableCollection<ThumbnailItem>();
        private ThumbnailItem dragSourceItem;
        private long _placeId;
        private long _universeId;
        private string _connectionString;
        private AssetRecord _currentPlace;
        private readonly AssetMetadataRepository _metadataRepo;
        private string _selectedIconPath;
        private string _selectedThumbnailPath;

        public PlaceEditWindow()
        {
            InitializeComponent();
            ThemeManager.InitializeThemeForWindow(this);
            Settings.Default.PropertyChanged += Settings_PropertyChanged;
            _connectionString = GetConnectionString();
            _metadataRepo = new AssetMetadataRepository();

            ThumbnailGalleryListBox.ItemsSource = thumbnailItems;

            for (int i = 1; i <= 100; i++)
            {
                MaxPlayersComboBox.Items.Add(new ComboBoxItem
                {
                    Content = i.ToString(),
                    IsSelected = i == 8
                });
            }

            SellGameAccessCheckBox.Checked += (s, e) => PricingPanel.IsEnabled = true;
            SellGameAccessCheckBox.Unchecked += (s, e) => PricingPanel.IsEnabled = false;
            AllowPrivateServersCheckBox.Checked += (s, e) => PrivateServerDetails.IsEnabled = true;
            AllowPrivateServersCheckBox.Unchecked += (s, e) => PrivateServerDetails.IsEnabled = false;
            PrivateServerPaidRadio.Checked += (s, e) => PrivateServerPricePanel.IsEnabled = true;
            PrivateServerFreeRadio.Checked += (s, e) => PrivateServerPricePanel.IsEnabled = false;
            PriceTextBox.TextChanged += (s, e) => UpdatePricing();
            PrivateServerPriceTextBox.TextChanged += (s, e) => UpdatePrivateServerPricing();
            CreateNewDevProductButton.Click += CreateNewDevProductButton_Click;
            SelectImageButton.Click += SelectImageButton_Click;
            UploadIconButton.Click += UploadIconButton_Click;
            SelectThumbnailImageButton.Click += SelectThumbnailImageButton_Click;
            UploadThumbnailImageButton.Click += UploadThumbnailImageButton_Click;
            UploadThumbnailVideoButton.Click += UploadThumbnailVideoButton_Click;
            SetAutoGeneratedThumbnailButton.Click += SetAutoGeneratedThumbnailButton_Click;
        }

        public PlaceEditWindow(long placeId) : this()
        {
            _placeId = placeId;
            Loaded += async (sender, e) => await LoadPlaceDataAsync();
        }

        private string GetConnectionString()
        {
            var cs = Properties.Settings.Default.DatabaseConnectionString;
            if (string.IsNullOrEmpty(cs))
                throw new InvalidOperationException("Database connection string is not configured in application settings.");
            return cs;
        }

        private async Task LoadPlaceDataAsync()
        {
            try
            {
                IsEnabled = false;
                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);

                if (_currentPlace == null)
                {
                    MessageBox.Show($"Asset with ID {_placeId} not found.", "Not Found",
                        MessageBoxButton.OK, MessageBoxImage.Warning);
                    Close();
                    return;
                }

                Title = $"Configure Place - {_currentPlace.Name} (ID: {_currentPlace.AssetId})";

                if (!_currentPlace.IsPlace)
                {
                    MessageBox.Show($"Asset ID {_placeId} is not a place. Editing has been disabled.",
                        "Not a Place", MessageBoxButton.OK, MessageBoxImage.Warning);
                }

                var universeId = await GamesRepository.GetUniverseIdFromPlaceIdAsync(_connectionString, _placeId);
                if (universeId.HasValue)
                {
                    _universeId = universeId.Value;
                }

                UpdateUIWithPlaceData();
                InitThumbnailRadioState();
                ThumbnailGalleryListBox.Visibility = ThumbnailAutoRadio.IsChecked == true ? Visibility.Collapsed : Visibility.Visible;
                await Task.WhenAll(
                    LoadGameIconAsync(),
                    LoadThumbnailsAsync(),
                    LoadDeveloperProductsAsync()
                );
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error loading place data: {ex.Message}", "Error",
                    MessageBoxButton.OK, MessageBoxImage.Error);
                Close();
            }
            finally
            {
                IsEnabled = true;
            }
        }

        private void UpdateUIWithPlaceData()
        {
            if (_currentPlace == null) return;

            var isPlace = _currentPlace.IsPlace;

            PlaceNameTextBox.Text = _currentPlace.Name ?? "";
            PlaceDescriptionTextBox.Text = _currentPlace.Description ?? "";
            SetGenreSelection(_currentPlace.Genre);

            SetDeviceCompatibility(_currentPlace.DeviceCompatibility);

            SellGameAccessCheckBox.IsChecked = _currentPlace.PaidAccessEnabled;
            PriceTextBox.Text = _currentPlace.PaidAccessPrice > 0 ? _currentPlace.PaidAccessPrice.ToString() : "";
            PricingPanel.IsEnabled = _currentPlace.PaidAccessEnabled;

            SetMaxPlayersSelection(_currentPlace.MaxVisitorCount);
            SetServerFillType(_currentPlace.ServerFillType);
            SetAccessType(_currentPlace.AccessType);

            AllowPrivateServersCheckBox.IsChecked = _currentPlace.PrivateServersAllowed;
            PrivateServerDetails.IsEnabled = _currentPlace.PrivateServersAllowed;
            if (_currentPlace.IsPrivateServersFree)
                PrivateServerFreeRadio.IsChecked = true;
            else
            {
                PrivateServerPaidRadio.IsChecked = true;
                PrivateServerPriceTextBox.Text = _currentPlace.PrivateServersPrice.ToString();
                PrivateServerPricePanel.IsEnabled = true;
            }

            SetGearPermissions(_currentPlace.IsAllGenresAllowed, _currentPlace.AllowedGearTypes);
            AllowCopyingCheckBox.IsChecked = _currentPlace.IsCopyingAllowed;

            AllowCopyInGameCheckBox.IsChecked = _currentPlace.AllowPlaceToBeCopiedInGame;
            AllowUpdateInGameCheckBox.IsChecked = _currentPlace.AllowPlaceToBeUpdatedInGame;

            if (_universeId > 0)
            {
                var universeInfo = GamesRepository.GetUniverseAsync(_connectionString, _universeId)
                    .GetAwaiter().GetResult();
                if (universeInfo != null)
                {
                    GameLink.NavigateUri = new Uri($"http://localhost/games/{_universeId}/");
                    GameLink.Inlines.Clear();
                    GameLink.Inlines.Add(universeInfo.Name ?? $"Universe {_universeId}");
                }
            }

            if (!isPlace)
            {
                DisableEditing();
            }
        }

        private void DisableEditing()
        {
            PlaceNameTextBox.IsEnabled = false;
            PlaceDescriptionTextBox.IsEnabled = false;
            GenreComboBox.IsEnabled = false;
            DeviceComputerCheckBox.IsEnabled = false;
            DevicePhoneCheckBox.IsEnabled = false;
            DeviceTabletCheckBox.IsEnabled = false;
            DeviceConsoleCheckBox.IsEnabled = false;
            SellGameAccessCheckBox.IsEnabled = false;
            PriceTextBox.IsEnabled = false;
            MaxPlayersComboBox.IsEnabled = false;
            ServerFillAutomaticRadio.IsEnabled = false;
            ServerFillEmptyRadio.IsEnabled = false;
            ServerFillCustomRadio.IsEnabled = false;
            AccessComboBox.IsEnabled = false;
            AllowPrivateServersCheckBox.IsEnabled = false;
            PrivateServerFreeRadio.IsEnabled = false;
            PrivateServerPaidRadio.IsEnabled = false;
            PrivateServerPriceTextBox.IsEnabled = false;
            GenreGearRadio.IsEnabled = false;
            AllGenresGearRadio.IsEnabled = false;
            GearMeleeCheckBox.IsEnabled = false;
            GearPowerUpsCheckBox.IsEnabled = false;
            GearRangedCheckBox.IsEnabled = false;
            GearNavigationCheckBox.IsEnabled = false;
            GearExplosivesCheckBox.IsEnabled = false;
            GearMusicalCheckBox.IsEnabled = false;
            GearSocialCheckBox.IsEnabled = false;
            GearTransportCheckBox.IsEnabled = false;
            GearBuildingCheckBox.IsEnabled = false;
            AllowCopyingCheckBox.IsEnabled = false;
            AllowCopyInGameCheckBox.IsEnabled = false;
            AllowUpdateInGameCheckBox.IsEnabled = false;
            CreateNewDevProductButton.IsEnabled = false;
            SaveButton.IsEnabled = false;
        }

        private void SetGenreSelection(int genreId)
        {
            var label = AssetGenreNames.GetGenreLabel(genreId);
            foreach (ComboBoxItem item in GenreComboBox.Items)
            {
                if (item.Content.ToString() == label)
                {
                    item.IsSelected = true;
                    return;
                }
            }
        }

        private void SetDeviceCompatibility(string deviceJson)
        {
            DeviceComputerCheckBox.IsChecked = false;
            DevicePhoneCheckBox.IsChecked = false;
            DeviceTabletCheckBox.IsChecked = false;
            DeviceConsoleCheckBox.IsChecked = false;

            if (string.IsNullOrWhiteSpace(deviceJson) || deviceJson == "[]") return;

            try
            {
                var ids = JsonSerializer.Deserialize<int[]>(deviceJson);
                if (ids == null) return;
                foreach (var id in ids)
                {
                    switch (id)
                    {
                        case 1: DeviceComputerCheckBox.IsChecked = true; break;
                        case 2: DeviceTabletCheckBox.IsChecked = true; break;
                        case 3: DevicePhoneCheckBox.IsChecked = true; break;
                        case 4: DeviceConsoleCheckBox.IsChecked = true; break;
                    }
                }
            }
            catch (Exception ex) { Console.WriteLine($"[ERROR] SetDeviceCompatibility: {ex}"); }
        }

        private void SetMaxPlayersSelection(int count)
        {
            foreach (ComboBoxItem item in MaxPlayersComboBox.Items)
            {
                if (item.Content.ToString() == count.ToString())
                {
                    item.IsSelected = true;
                    return;
                }
            }
        }

        private void SetServerFillType(int fillType)
        {
            ServerFillAutomaticRadio.IsChecked = fillType == 0;
            ServerFillEmptyRadio.IsChecked = fillType == 1;
            ServerFillCustomRadio.IsChecked = fillType == 2;
        }

        private void SetAccessType(int accessType)
        {
            foreach (ComboBoxItem item in AccessComboBox.Items)
            {
                if (accessType == 1 && item.Content.ToString() == "Everyone")
                { item.IsSelected = true; return; }
                if (accessType == 2 && item.Content.ToString() == "Friends")
                { item.IsSelected = true; return; }
            }
        }

        private void SetGearPermissions(bool isAllGenres, string allowedGearTypes)
        {
            AllGenresGearRadio.IsChecked = isAllGenres;
            GenreGearRadio.IsChecked = !isAllGenres;

            GearMeleeCheckBox.IsChecked = false;
            GearPowerUpsCheckBox.IsChecked = false;
            GearRangedCheckBox.IsChecked = false;
            GearNavigationCheckBox.IsChecked = false;
            GearExplosivesCheckBox.IsChecked = false;
            GearMusicalCheckBox.IsChecked = false;
            GearSocialCheckBox.IsChecked = false;
            GearTransportCheckBox.IsChecked = false;
            GearBuildingCheckBox.IsChecked = false;

            if (string.IsNullOrWhiteSpace(allowedGearTypes) || allowedGearTypes == "[]") return;

            try
            {
                var gears = JsonSerializer.Deserialize<int[]>(allowedGearTypes);
                if (gears == null) return;
                foreach (var g in gears)
                {
                    switch (g)
                    {
                        case 1: GearMeleeCheckBox.IsChecked = true; break;
                        case 2: GearPowerUpsCheckBox.IsChecked = true; break;
                        case 3: GearRangedCheckBox.IsChecked = true; break;
                        case 4: GearNavigationCheckBox.IsChecked = true; break;
                        case 5: GearExplosivesCheckBox.IsChecked = true; break;
                        case 6: GearMusicalCheckBox.IsChecked = true; break;
                        case 7: GearSocialCheckBox.IsChecked = true; break;
                        case 8: GearTransportCheckBox.IsChecked = true; break;
                        case 9: GearBuildingCheckBox.IsChecked = true; break;
                    }
                }
            }
            catch (Exception ex) { Console.WriteLine($"[ERROR] SetGearPermissions: {ex}"); }
        }

        private async Task LoadDeveloperProductsAsync()
        {
            try
            {
                if (_universeId <= 0) return;

                var products = await DevProductHandler.GetDeveloperProductsByUniverse(_connectionString, _universeId);
                DevProductsListView.ItemsSource = products.Select(p => new DevProductDisplayItem
                {
                    Id = p.Id,
                    Name = p.Name,
                    Price = $"{p.PriceInRobux} Robux"
                }).ToList();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error loading developer products: {ex.Message}");
            }
        }

        private BitmapImage LoadBitmapFromUrlOrLocal(string url)
        {
            if (string.IsNullOrWhiteSpace(url))
                return null;
            try
            {
                var bitmap = new BitmapImage();
                bitmap.BeginInit();
                bitmap.UriSource = new Uri(url);
                bitmap.CacheOption = BitmapCacheOption.OnLoad;
                bitmap.EndInit();
                if (bitmap.CanFreeze) bitmap.Freeze();
                return bitmap;
            }
            catch
            {
                try
                {
                    var fileName = url.Split('/').LastOrDefault();
                    if (!string.IsNullOrWhiteSpace(fileName))
                    {
                        var searchDirs = new[]
                        {
                            System.IO.Path.Combine(Settings.Default.AssetsDirectory, "place-icons"),
                            System.IO.Path.Combine(Settings.Default.AssetsDirectory, "place-thumbnails"),
                            System.IO.Path.Combine(Settings.Default.ThumbnailsOutputDirectory, "place-icons"),
                            System.IO.Path.Combine(Settings.Default.ThumbnailsOutputDirectory, "place-thumbnails"),
                        };
                        foreach (var dir in searchDirs)
                        {
                            var localPath = System.IO.Path.Combine(dir, fileName);
                            if (File.Exists(localPath))
                            {
                                var bitmap = new BitmapImage();
                                bitmap.BeginInit();
                                bitmap.UriSource = new Uri(localPath, UriKind.Absolute);
                                bitmap.CacheOption = BitmapCacheOption.OnLoad;
                                bitmap.EndInit();
                                if (bitmap.CanFreeze) bitmap.Freeze();
                                return bitmap;
                            }
                        }
                    }
                }
                catch (Exception ex) { Console.WriteLine($"[ERROR] LoadBitmapFromUrlOrLocal: {ex}"); }
                return null;
            }
        }

        private async Task LoadGameIconAsync()
        {
            try
            {
                bool hasCustom = _currentPlace?.CustomIcon == true && !string.IsNullOrWhiteSpace(_currentPlace?.PlaceCustomIconUrl);
                bool hasGenerated = _currentPlace?.GeneratedIcon == true && !string.IsNullOrWhiteSpace(_currentPlace?.PlaceGeneratedIconUrl);

                if (hasCustom)
                {
                    var bmp = LoadBitmapFromUrlOrLocal(_currentPlace.PlaceCustomIconUrl);
                    GameIconImage.Source = bmp;
                    IconImageRadio.IsChecked = true;
                    IconAutoGeneratedRadio.IsChecked = false;
                }
                else if (hasGenerated)
                {
                    var bmp = LoadBitmapFromUrlOrLocal(_currentPlace.PlaceGeneratedIconUrl);
                    GameIconImage.Source = bmp;
                    IconImageRadio.IsChecked = false;
                    IconAutoGeneratedRadio.IsChecked = true;
                }
                else
                {
                    GameIconImage.Source = null;
                    IconImageRadio.IsChecked = false;
                    IconAutoGeneratedRadio.IsChecked = false;
                }

                if (hasGenerated)
                {
                    var bmp = LoadBitmapFromUrlOrLocal(_currentPlace.PlaceGeneratedIconUrl);
                    AutoGeneratedIconImage.Source = bmp;
                }
                else
                {
                    AutoGeneratedIconImage.Source = null;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error loading game icon: {ex.Message}");
            }
        }

        private void InitThumbnailRadioState()
        {
            ThumbnailImageRadio.IsChecked = _currentPlace?.PlaceCustomThumbnail == true;
            ThumbnailVideoRadio.IsChecked = _currentPlace?.PlaceVideoThumbnail == true;
            ThumbnailAutoRadio.IsChecked = _currentPlace?.PlaceAutoGeneratedThumbnail == true;
        }

        private async Task LoadThumbnailsAsync()
        {
            try
            {
                thumbnailItems.Clear();

                string autoGenUrl = _currentPlace?.PlaceGeneratedThumbnailUrl;
                bool hasAutoGen = ThumbnailAutoRadio.IsChecked == true && !string.IsNullOrWhiteSpace(autoGenUrl);

                if (!string.IsNullOrWhiteSpace(_currentPlace?.PlaceThumbnailVideo))
                {
                    ThumbnailVideoLinkTextBox.Text = _currentPlace.PlaceThumbnailVideo;
                }

                if (hasAutoGen)
                {
                    var bmp = LoadBitmapFromUrlOrLocal(autoGenUrl);
                    if (bmp != null)
                    {
                        thumbnailItems.Add(new ThumbnailItem { ImageSource = bmp });
                        AutoGeneratedThumbnailImage.Source = bmp;
                    }
                }
                else if (ThumbnailImageRadio.IsChecked == true)
                {
                    AutoGeneratedThumbnailImage.Source = null;
                    var entries = await PlaceThumbnail.GetPlaceImageThumbnailsAsync(_connectionString, _placeId);
                    foreach (var entry in entries)
                    {
                        var bmp = LoadBitmapFromUrlOrLocal(entry.Url);
                        if (bmp != null)
                            thumbnailItems.Add(new ThumbnailItem { Id = entry.Id, ImageSource = bmp });
                    }
                }
                else
                {
                    AutoGeneratedThumbnailImage.Source = null;
                }

                UpdateMainPreview();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Error loading thumbnails: {ex.Message}");
            }
        }

        private void UpdateMainPreview()
        {
            ThumbnailPreviewImage.Source = thumbnailItems.Count > 0 ? thumbnailItems[0].ImageSource : null;
        }

        private void SelectImageButton_Click(object sender, RoutedEventArgs e)
        {
            var dialog = new OpenFileDialog
            {
                Title = "Select Game Icon Image",
                Filter = "Image Files (*.png;*.jpg;*.jpeg;*.gif;*.bmp)|*.png;*.jpg;*.jpeg;*.gif;*.bmp"
            };
            if (dialog.ShowDialog() == true)
            {
                _selectedIconPath = dialog.FileName;
                SelectedImageIndicator.Text = System.IO.Path.GetFileName(_selectedIconPath);
                try
                {
                    var bitmap = new BitmapImage();
                    bitmap.BeginInit();
                    bitmap.UriSource = new Uri(_selectedIconPath);
                    bitmap.CacheOption = BitmapCacheOption.OnLoad;
                    bitmap.EndInit();
                    GameIconImage.Source = bitmap;
                }
                catch (Exception ex) { Console.WriteLine($"[ERROR] SelectIconButton_Click preview: {ex}"); }
            }
        }

        private async void UploadIconButton_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(_selectedIconPath))
            {
                MessageBox.Show("Please select an image first using the 'Select Image' button.", "No Image Selected", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            try
            {
                UploadIconButton.IsEnabled = false;

                var baseUrl = Settings.Default.ThumbnailUrl;
                if (string.IsNullOrWhiteSpace(baseUrl))
                    baseUrl = $"http://{Settings.Default.WebsiteHost}:{Settings.Default.WebsitePort}";

                var fileBytes = File.ReadAllBytes(_selectedIconPath);
                var resizedBytes = PlaceThumbnail.ResizeImage(fileBytes, 110, 110);
                var fileHash = HashingUtilities.GenerateFileHash(resizedBytes);

                var iconDir = System.IO.Path.Combine(Settings.Default.AssetsDirectory, "place-icons");
                System.IO.Directory.CreateDirectory(iconDir);
                var localIconPath = System.IO.Path.Combine(iconDir, $"{fileHash}.png");
                File.WriteAllBytes(localIconPath, resizedBytes);

                var iconUrl = $"{baseUrl.TrimEnd('/')}/{fileHash}.png";

                await PlaceThumbnail.SetPlaceCustomIconAsync(_connectionString, _placeId, iconUrl, iconUrl, fileHash);

                var bitmap = new BitmapImage();
                bitmap.BeginInit();
                bitmap.UriSource = new Uri(localIconPath, UriKind.Absolute);
                bitmap.CacheOption = BitmapCacheOption.OnLoad;
                bitmap.EndInit();
                GameIconImage.Source = bitmap;

                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);
                _selectedIconPath = null;
                SelectedImageIndicator.Text = "No file selected";
                MessageBox.Show("Icon uploaded successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error uploading icon: {ex.Message}", "Upload Failed", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                UploadIconButton.IsEnabled = true;
            }
        }

        private async void SetAutoGeneratedIconButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var result = MessageBox.Show("Set the icon back to the auto-generated image? This will remove any custom icon.", "Confirm", MessageBoxButton.YesNo, MessageBoxImage.Question);
                if (result != MessageBoxResult.Yes)
                    return;

                var phUrl = _currentPlace?.PlaceCustomIconUrl ?? _currentPlace?.ThumbnailUrl ?? "placeholder";
                await PlaceThumbnail.ClearPlaceIconAsync(_connectionString, _placeId, phUrl);

                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);
                await LoadGameIconAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error setting auto-generated icon: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void SelectThumbnailImageButton_Click(object sender, RoutedEventArgs e)
        {
            var dialog = new OpenFileDialog
            {
                Title = "Select Thumbnail Image",
                Filter = "Image Files (*.png;*.jpg;*.jpeg;*.gif;*.bmp)|*.png;*.jpg;*.jpeg;*.gif;*.bmp"
            };
            if (dialog.ShowDialog() == true)
            {
                _selectedThumbnailPath = dialog.FileName;
                SelectedThumbnailIndicator.Text = System.IO.Path.GetFileName(_selectedThumbnailPath);
            }
        }

        private async void UploadThumbnailImageButton_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(_selectedThumbnailPath))
            {
                MessageBox.Show("Please select an image first using the 'Select Image' button.", "No Image Selected", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            try
            {
                UploadThumbnailImageButton.IsEnabled = false;
                var baseUrl = Settings.Default.ThumbnailUrl;
                if (string.IsNullOrWhiteSpace(baseUrl))
                    baseUrl = $"http://{Settings.Default.WebsiteHost}:{Settings.Default.WebsitePort}";

                var fileBytes = File.ReadAllBytes(_selectedThumbnailPath);
                var resizedBytes = PlaceThumbnail.ResizeImage(fileBytes, 1280, 720);
                var fileHash = HashingUtilities.GenerateFileHash(resizedBytes);

                var thumbDir = System.IO.Path.Combine(Settings.Default.AssetsDirectory, "place-thumbnails");
                System.IO.Directory.CreateDirectory(thumbDir);
                var localThumbPath = System.IO.Path.Combine(thumbDir, $"{fileHash}.png");
                File.WriteAllBytes(localThumbPath, resizedBytes);

                var thumbnailUrl = $"{baseUrl.TrimEnd('/')}/{fileHash}.png";
                var placeName = _currentPlace?.Name ?? $"Place{_placeId}";
                await PlaceThumbnail.DeleteAutoGeneratedThumbnailEntriesAsync(_connectionString, _placeId);
                await PlaceThumbnail.AddThumbnailImageAsync(_connectionString, _placeId, placeName, thumbnailUrl, fileHash);
                await PlaceThumbnail.UpdatePlaceThumbnailFlagsAsync(_connectionString, _placeId, true, false, false);
                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);
                _selectedThumbnailPath = null;
                SelectedThumbnailIndicator.Text = "No file selected";
                await LoadThumbnailsAsync();
                MessageBox.Show("Thumbnail uploaded successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error uploading thumbnail: {ex.Message}", "Upload Failed", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                UploadThumbnailImageButton.IsEnabled = true;
            }
        }

        private async void UploadThumbnailVideoButton_Click(object sender, RoutedEventArgs e)
        {
            var videoUrl = ThumbnailVideoLinkTextBox?.Text?.Trim();
            if (string.IsNullOrWhiteSpace(videoUrl))
            {
                MessageBox.Show("Please enter a YouTube video URL.", "No URL", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }
            if (!YouTubeUtilities.IsValidYouTubeURL(videoUrl))
            {
                MessageBox.Show("The provided URL is not a valid YouTube URL.", "Invalid URL", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            try
            {
                UploadThumbnailVideoButton.IsEnabled = false;
                await PlaceThumbnail.DeleteAutoGeneratedThumbnailEntriesAsync(_connectionString, _placeId);
                await PlaceThumbnail.SetPlaceVideoUrlTempAsync(_connectionString, _placeId, videoUrl);
                await PlaceThumbnail.UpdatePlaceThumbnailFlagsAsync(_connectionString, _placeId, false, true, false);
                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);
                await LoadThumbnailsAsync();
                MessageBox.Show("Video thumbnail set successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error setting video thumbnail: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                UploadThumbnailVideoButton.IsEnabled = true;
            }
        }

        private async void SetAutoGeneratedThumbnailButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                var result = MessageBox.Show("Set the primary thumbnail back to the auto-generated image?", "Confirm", MessageBoxButton.YesNo, MessageBoxImage.Question);
                if (result != MessageBoxResult.Yes)
                    return;

                var autoGenUrl = _currentPlace?.PlaceGeneratedThumbnailUrl;
                if (string.IsNullOrWhiteSpace(autoGenUrl))
                {
                    MessageBox.Show("No auto-generated thumbnail URL is available for this place.", "Unavailable", MessageBoxButton.OK, MessageBoxImage.Information);
                    return;
                }

                await PlaceThumbnail.DeleteAutoGeneratedThumbnailEntriesAsync(_connectionString, _placeId);
                await PlaceThumbnail.UpdatePlaceThumbnailFlagsAsync(_connectionString, _placeId, false, false, true);
                _currentPlace = await _metadataRepo.GetAssetByIdAsync(_connectionString, _placeId);
                await LoadThumbnailsAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error setting auto-generated thumbnail: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void UpdatePricing()
        {
            if (int.TryParse(PriceTextBox.Text, out int price) && price > 0)
            {
                int fee = (int)Math.Round(price * 0.3);
                int profit = price - fee;
                MarketplaceFeeText.Text = fee.ToString();
                ProfitText.Text = profit.ToString();
            }
            else
            {
                MarketplaceFeeText.Text = "0";
                ProfitText.Text = "0";
            }
        }

        private void UpdatePrivateServerPricing()
        {
            if (int.TryParse(PrivateServerPriceTextBox.Text, out int price) && price > 0)
            {
                int fee = (int)Math.Round(price * 0.3);
                int profit = price - fee;
                PrivateServerFeeText.Text = fee.ToString();
                PrivateServerProfitText.Text = profit.ToString();
            }
            else
            {
                PrivateServerFeeText.Text = "0";
                PrivateServerProfitText.Text = "0";
            }
        }

        private async void SaveButton_Click(object sender, RoutedEventArgs e)
        {
            if (_currentPlace == null || !_currentPlace.IsPlace) return;

            try
            {
                SaveButton.IsEnabled = false;

                var deviceIds = new System.Collections.Generic.List<int>();
                if (DeviceComputerCheckBox.IsChecked == true) deviceIds.Add(1);
                if (DeviceTabletCheckBox.IsChecked == true) deviceIds.Add(2);
                if (DevicePhoneCheckBox.IsChecked == true) deviceIds.Add(3);
                if (DeviceConsoleCheckBox.IsChecked == true) deviceIds.Add(4);
                var deviceJson = JsonSerializer.Serialize(deviceIds);

                var gearIds = new System.Collections.Generic.List<int>();
                if (GearMeleeCheckBox.IsChecked == true) gearIds.Add(1);
                if (GearPowerUpsCheckBox.IsChecked == true) gearIds.Add(2);
                if (GearRangedCheckBox.IsChecked == true) gearIds.Add(3);
                if (GearNavigationCheckBox.IsChecked == true) gearIds.Add(4);
                if (GearExplosivesCheckBox.IsChecked == true) gearIds.Add(5);
                if (GearMusicalCheckBox.IsChecked == true) gearIds.Add(6);
                if (GearSocialCheckBox.IsChecked == true) gearIds.Add(7);
                if (GearTransportCheckBox.IsChecked == true) gearIds.Add(8);
                if (GearBuildingCheckBox.IsChecked == true) gearIds.Add(9);
                var gearJson = JsonSerializer.Serialize(gearIds);

                int genreId = AssetGenreNames.GetGenreIdFromString(
                    (GenreComboBox.SelectedItem as ComboBoxItem)?.Content?.ToString() ?? "All");

                int maxPlayers = 8;
                if (MaxPlayersComboBox.SelectedItem is ComboBoxItem maxItem)
                    int.TryParse(maxItem.Content?.ToString(), out maxPlayers);

                int accessType = (AccessComboBox.SelectedItem as ComboBoxItem)?.Content?.ToString() == "Friends" ? 2 : 1;

                int serverFill = ServerFillAutomaticRadio.IsChecked == true ? 0
                    : ServerFillEmptyRadio.IsChecked == true ? 1 : 2;

                bool paidAccess = SellGameAccessCheckBox.IsChecked == true;
                int paidAccessPrice = 0;
                if (paidAccess && int.TryParse(PriceTextBox.Text, out int pPrice))
                    paidAccessPrice = pPrice;

                bool psAllowed = AllowPrivateServersCheckBox.IsChecked == true;
                bool psFree = PrivateServerFreeRadio.IsChecked == true;
                int psPrice = 0;
                if (psAllowed && !psFree && int.TryParse(PrivateServerPriceTextBox.Text, out int psP))
                    psPrice = psP;

                bool isAllGenres = AllGenresGearRadio.IsChecked == true;

                var settings = new PlaceSettingsData
                {
                    PlaceId = _placeId,
                    Name = PlaceNameTextBox.Text ?? "",
                    Description = PlaceDescriptionTextBox.Text ?? "",
                    Genre = genreId,
                    DeviceCompatibility = deviceJson,
                    MaxVisitorCount = maxPlayers,
                    ServerFillType = serverFill,
                    AccessType = accessType,
                    PrivateServersAllowed = psAllowed,
                    PrivateServersFree = psFree,
                    PrivateServersPrice = psPrice,
                    PaidAccessEnabled = paidAccess,
                    PaidAccessPrice = paidAccessPrice,
                    IsCopyingAllowed = AllowCopyingCheckBox.IsChecked == true,
                    IsAllGenresAllowed = isAllGenres,
                    AllowedGearTypes = gearJson,
                    AllowPlaceToBeCopiedInGame = AllowCopyInGameCheckBox.IsChecked == true,
                    AllowPlaceToBeUpdatedInGame = AllowUpdateInGameCheckBox.IsChecked == true,
                    CustomIcon = IconImageRadio.IsChecked == true,
                    GeneratedIcon = IconAutoGeneratedRadio.IsChecked == true,
                    PlaceCustomThumbnail = ThumbnailImageRadio.IsChecked == true,
                    PlaceVideoThumbnail = ThumbnailVideoRadio.IsChecked == true,
                    PlaceAutoGeneratedThumbnail = ThumbnailAutoRadio.IsChecked == true
                };

                await GameCreationService.UpdatePlaceAllSettingsAsync(_connectionString, settings);
                await PlaceThumbnail.DeleteAutoGeneratedThumbnailEntriesAsync(_connectionString, _placeId);

                var sortIds = thumbnailItems
                    .Where(t => t.Id > 0)
                    .Select(t => t.Id)
                    .ToList();
                if (sortIds.Count > 0)
                    await PlaceThumbnail.UpdateThumbnailSortOrderAsync(_connectionString, _placeId, sortIds);

                DialogResult = true;
                Close();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error saving place settings: {ex.Message}",
                    "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                SaveButton.IsEnabled = true;
            }
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }

        private void ThumbnailGalleryListBox_PreviewMouseMove(object sender, System.Windows.Input.MouseEventArgs e)
        {
            if (e.LeftButton == System.Windows.Input.MouseButtonState.Pressed)
            {
                var listBox = sender as ListBox;
                var item = listBox?.SelectedItem as ThumbnailItem;
                if (item != null)
                {
                    dragSourceItem = item;
                    DragDrop.DoDragDrop(listBox, item, DragDropEffects.Move);
                }
            }
        }

        private void ThumbnailGalleryListBox_DragOver(object sender, DragEventArgs e)
        {
            e.Effects = DragDropEffects.Move;
            e.Handled = true;
        }

        private void ThumbnailGalleryListBox_Drop(object sender, DragEventArgs e)
        {
            var droppedItem = e.Data.GetData(typeof(ThumbnailItem)) as ThumbnailItem;
            if (droppedItem == null || dragSourceItem == null) return;

            var listBox = sender as ListBox;
            if (listBox == null) return;

            int oldIndex = thumbnailItems.IndexOf(dragSourceItem);
            if (oldIndex < 0) return;

            var dropPoint = e.GetPosition(listBox);
            var hitResult = System.Windows.Media.VisualTreeHelper.HitTest(listBox, dropPoint);
            if (hitResult == null) return;

            DependencyObject obj = hitResult.VisualHit;
            while (obj != null && !(obj is ListBoxItem))
            {
                obj = System.Windows.Media.VisualTreeHelper.GetParent(obj);
            }

            if (obj is ListBoxItem targetItem)
            {
                int newIndex = listBox.ItemContainerGenerator.IndexFromContainer(targetItem);
                if (newIndex >= 0 && newIndex < thumbnailItems.Count && newIndex != oldIndex)
                {
                    thumbnailItems.Move(oldIndex, newIndex);
                    UpdateMainPreview();
                }
            }

            dragSourceItem = null;
        }

        private void ThumbnailGalleryListBox_MouseLeftButtonUp(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            var listBox = sender as ListBox;
            if (listBox?.SelectedItem is ThumbnailItem selected)
                ThumbnailPreviewImage.Source = selected.ImageSource;
        }

        private async void DeleteThumbnail_Click(object sender, RoutedEventArgs e)
        {
            if (!(sender is Button) || !((sender as Button).Tag is ThumbnailItem))
                return;
            var item = (ThumbnailItem)((Button)sender).Tag;
            if (item.Id <= 0)
            {
                thumbnailItems.Remove(item);
                UpdateMainPreview();
                return;
            }
            try
            {
                var removed = await PlaceThumbnail.RemoveThumbnailAsync(_connectionString, _placeId, item.Id);
                if (removed)
                {
                    thumbnailItems.Remove(item);
                    UpdateMainPreview();
                }
                else
                    MessageBox.Show("Failed to delete thumbnail from database.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Error deleting thumbnail: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        public static PlaceEditWindow PlaceSelectWindow(int placeId)
        {
            if (placeId <= 0)
            {
                MessageBox.Show("Invalid Place ID provided.", "Invalid Input",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return null;
            }

            var window = new PlaceEditWindow(placeId);
            window.Show();
            return window;
        }

        private void Tab_Click(object sender, RoutedEventArgs e)
        {
            var tab = sender as RadioButton;
            if (tab == null) return;

            BasicSettingsContent.Visibility = Visibility.Collapsed;
            GameIconContent.Visibility = Visibility.Collapsed;
            ThumbnailsContent.Visibility = Visibility.Collapsed;
            AccessContent.Visibility = Visibility.Collapsed;
            PermissionsContent.Visibility = Visibility.Collapsed;
            DeveloperProductsContent.Visibility = Visibility.Collapsed;
            GamesContent.Visibility = Visibility.Collapsed;

            if (tab == BasicSettingsTab)
                BasicSettingsContent.Visibility = Visibility.Visible;
            else if (tab == GameIconTab)
                GameIconContent.Visibility = Visibility.Visible;
            else if (tab == ThumbnailsTab)
                ThumbnailsContent.Visibility = Visibility.Visible;
            else if (tab == AccessTab)
                AccessContent.Visibility = Visibility.Visible;
            else if (tab == PermissionsTab)
                PermissionsContent.Visibility = Visibility.Visible;
            else if (tab == DeveloperProductsTab)
                DeveloperProductsContent.Visibility = Visibility.Visible;
            else if (tab == GamesTab)
                GamesContent.Visibility = Visibility.Visible;
        }

        private void IconType_Changed(object sender, RoutedEventArgs e)
        {
            if (IconImageUploadSection == null || AutoGeneratedPanel == null) return;
            bool isImage = IconImageRadio.IsChecked == true;
            IconImageUploadSection.Visibility = isImage ? Visibility.Visible : Visibility.Collapsed;
            AutoGeneratedPanel.Visibility = isImage ? Visibility.Collapsed : Visibility.Visible;
        }

        private async void ThumbnailType_Changed(object sender, RoutedEventArgs e)
        {
            if (ThumbnailImageUploadPanel == null || ThumbnailVideoUploadPanel == null || ThumbnailAutoPanel == null) return;
            ThumbnailImageUploadPanel.Visibility = ThumbnailImageRadio.IsChecked == true ? Visibility.Visible : Visibility.Collapsed;
            ThumbnailVideoUploadPanel.Visibility = ThumbnailVideoRadio.IsChecked == true ? Visibility.Visible : Visibility.Collapsed;
            ThumbnailAutoPanel.Visibility = ThumbnailAutoRadio.IsChecked == true ? Visibility.Visible : Visibility.Collapsed;
            ThumbnailGalleryListBox.Visibility = ThumbnailImageRadio.IsChecked == true ? Visibility.Visible : Visibility.Collapsed;
            await LoadThumbnailsAsync();
        }

        private void CreateNewDevProductButton_Click(object sender, RoutedEventArgs e)
        {
            if (_universeId <= 0)
            {
                MessageBox.Show("This place is not part of a universe. Cannot create developer products.", "No Universe",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            var window = new CreateDeveloperProductWindow(_connectionString, _universeId);
            if (window.ShowDialog() == true)
            {
                _ = LoadDeveloperProductsAsync();
            }
        }

        private void EditDevProduct_Click(object sender, RoutedEventArgs e)
        {
            if (sender is Button button && button.Tag is long productId)
            {
                var window = new EditDeveloperProductWindow(_connectionString, _universeId, productId);
                if (window.ShowDialog() == true)
                {
                    _ = LoadDeveloperProductsAsync();
                }
            }
        }

        private void Settings_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "Theme" || e.PropertyName == "ColorScheme" || e.PropertyName == "BackgroundColor")
            {
                ThemeManager.InitializeThemeForWindow(this);
            }
        }
    }
}
