//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roblox.Thumbnails.Relay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roblox.Thumbnails.Relay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Closeup v1.0.3
        ///-- Used for avatar closeup (aka &quot;headshot&quot;)
        ///local baseUrl, characterAppearanceUrl, fileExtension, x, y, quadratic, baseHatZoom, maxHatZoom, cameraOffsetX, cameraOffsetY = ...
        ///
        ///local FFlagOnlyCheckHeadAccessoryInHeadShot = game:DefineFastFlag(&quot;OnlyCheckHeadAccessoryInHeadShot&quot;, false)
        ///local FFlagNewHeadshotLighting = game:DefineFastFlag(&quot;NewHeadshotLighting&quot;, false)
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptSt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvatarHeadShotScript {
            get {
                return ResourceManager.GetString("AvatarHeadShotScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Avatar v1.0.2
        ///-- This is the thumbnail script for R6 avatars. Straight up and down, with the right arm out if they have a gear.
        ///
        ///local characterAppearanceUrl, baseUrl, fileExtension, x, y = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local player = game:GetService(&quot;Players&quot;):Crea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvatarScript {
            get {
                return ResourceManager.GetString("AvatarScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Decal v1.0.2
        ///-- Used for faces and decals
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&apos;ScriptContext&apos;).ScriptsDisabled = true
        ///
        ///local decal = game:GetObjects(assetUrl)[1]
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;DecalLoaded&quot;)
        ///
        ///local image, requestedUrls
        ///local success = pc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FaceScript {
            get {
                return ResourceManager.GetString("FaceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Gear v1.0.3
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///for _, object in pairs(game:GetObjects(assetUrl)) do
        ///	object.Parent = workspace
        ///end
        ///
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ObjectsLoaded&quot;)
        ///
        ///local result, requestedUrls = T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GearScript {
            get {
                return ResourceManager.GetString("GearScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Hat v1.0.6
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local accoutrement = game:GetObjects(assetUrl)[1]
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ObjectsLoaded&quot;)
        ///
        ///accoutrement.Parent = workspace
        ///
        ///local result, requestedUrls = Thum [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HatScript {
            get {
                return ResourceManager.GetString("HatScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Head v1.8.0
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl, mannequinId = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local objects = game:GetObjects(assetUrl)
        ///
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ObjectsLoaded&quot;)
        ///
        ///local mannequin = game:GetObjects(baseUrl.. &quot;asset/?id=&quot; ..  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HeadScript {
            get {
                return ResourceManager.GetString("HeadScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- MeshPart v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///game:DefineFastFlag(&quot;OnlyAllowMeshParts&quot;, false)
        ///
        ///for _, object in pairs(game:GetObjects(assetUrl)) do
        ///	if game:GetFastFlag(&quot;OnlyAllowMeshParts&quot;) then
        ///		if object:IsA(&quot;MeshP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MeshPartScript {
            get {
                return ResourceManager.GetString("MeshPartScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Mesh v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local part = Instance.new(&quot;Part&quot;)
        ///part.Parent = workspace
        ///
        ///local specialMesh = Instance.new(&quot;SpecialMesh&quot;)
        ///specialMesh.MeshId = assetUrl
        ///specialMesh.Parent = part
        ///
        ///local result [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MeshScript {
            get {
                return ResourceManager.GetString("MeshScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Model v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///for _, object in pairs(game:GetObjects(assetUrl)) do
        ///	if object:IsA(&quot;Sky&quot;) then
        ///		local resultValues = nil
        ///		local success = pcall(function() resultValues = {ThumbnailGenerato [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ModelScript {
            get {
                return ResourceManager.GetString("ModelScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Package v1.1.7
        ///-- See http://wiki.roblox.com/index.php?title=R15_Compatibility_Guide#Package_Parts for details on how body parts work with R15
        ///
        ///local assetUrls, baseUrl, fileExtension, x, y, R6RigUrl, customTextureUrls = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local function  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PackageScript {
            get {
                return ResourceManager.GetString("PackageScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Pants v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl, mannequinId = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///0
        ///local mannequin = game:GetObjects(baseUrl.. &quot;asset/?id=&quot; .. tostring(mannequinId))[1]
        ///mannequin.Humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PantsScript {
            get {
                return ResourceManager.GetString("PantsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Place v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl, universeId = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///if universeId ~= nil then
        ///	pcall(function() game:SetUniverseId(universeId) end)
        ///end
        ///
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///game:GetService(&quot;StarterGui&quot;).ShowDevelopmentGui = false
        ///
        ///game:Load(assetUrl)
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlaceScript {
            get {
                return ResourceManager.GetString("PlaceScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Shirt v1.0.2
        ///
        ///local assetUrl, fileExtension, x, y, baseUrl, mannequinId = ...
        ///
        ///local ThumbnailGenerator = game:GetService(&quot;ThumbnailGenerator&quot;)
        ///ThumbnailGenerator:AddProfilingCheckpoint(&quot;ThumbnailScriptStarted&quot;)
        ///
        ///pcall(function() game:GetService(&quot;ContentProvider&quot;):SetBaseUrl(baseUrl) end)
        ///game:GetService(&quot;ScriptContext&quot;).ScriptsDisabled = true
        ///
        ///local mannequin = game:GetObjects(baseUrl.. &quot;asset/?id=&quot; .. tostring(mannequinId))[1]
        ///mannequin.Humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.No [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShirtScript {
            get {
                return ResourceManager.GetString("ShirtScript", resourceCulture);
            }
        }
    }
}
