<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Control_Panel</RootNamespace>
    <AssemblyName>Control Panel</AssemblyName>
    <ApplicationIcon>ControlPanel.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
      </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <!-- Reference to other project assemblies -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\Assemblies\Assets\Assets.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Avatar\Avatar.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Catalog\Catalog.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Common\Common.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Economy\Economy.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Thumbnails\Thumbnails.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Games\Games.csproj" />
    <ProjectReference Include="..\..\..\Assemblies\Users\Users.csproj" />
    <!-- Add more assembly references as needed -->
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="Views\App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ControlPanel.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="5.0.0" />
    <PackageReference Include="Fody" Version="6.8.0">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.4" />
	<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>

</Project>
