using System;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;

namespace Assets
{
    public sealed class AssetMetadataRepository
    {
        public async Task<AssetRecord?> GetAssetByIdAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using (var conn = new NpgsqlConnection(connectionString))
            {
                await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

                const string sql = @"select asset_id, name, asset_type_id, owner_user_id, content_hash, file_extension, content_type, thumbnail_url, high_res_thumbnail_url, description, asset_image, asset_link, on_sale, price, price_in_tix, limited_unique, limited_quantity, limited_remaining, limited_until, allow_comments, genre, is_place, privacy_level, custom_icon, place_custom_icon_url, place_custom_icon_high_res_url, place_custom_icon_hash, generated_icon, place_generated_icon_url, place_generated_icon_high_res_url, place_generated_icon_hash, place_autogenerated_thumbnail, place_generated_thumbnail_url, place_custom_thumbnail, place_video_thumbnail, place_thumbnail_video, max_visitor_count, device_compatibility, server_fill_type, number_of_custom_social_slots, access_type, private_servers_allowed, private_servers_free, private_servers_price, paid_access_enabled, paid_access_price, is_copying_allowed, is_all_genres_allowed, allowed_gear_types, allow_place_to_be_copied_in_game, allow_place_to_be_updated_in_game, recent_average_price
from assets
where asset_id = @id";

                using (var cmd = new NpgsqlCommand(sql, conn))
                {
                    cmd.Parameters.AddWithValue("id", assetId);

                    using (var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
                    {
                        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                            return null;

                        var record = new AssetRecord
                        {
                            AssetId = reader.GetInt64(0),
                            Name = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            AssetTypeId = reader.IsDBNull(2) ? 0 : reader.GetInt32(2),
                            OwnerUserId = reader.IsDBNull(3) ? 0 : reader.GetInt64(3),
                            ContentHash = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                            FileExtension = reader.IsDBNull(5) ? null : reader.GetString(5),
                            ContentType = reader.IsDBNull(6) ? null : reader.GetString(6),
                            ThumbnailUrl = reader.IsDBNull(7) ? null : reader.GetString(7),
                            HighResThumbnailUrl = reader.IsDBNull(8) ? null : reader.GetString(8),
                            Description = reader.IsDBNull(9) ? null : reader.GetString(9),
                            AssetImage = !reader.IsDBNull(10) && reader.GetBoolean(10),
                            AssetLink = reader.IsDBNull(11) ? (long?)null : reader.GetInt64(11),
                            OnSale = !reader.IsDBNull(12) && reader.GetBoolean(12),
                            Price = reader.IsDBNull(13) ? 0L : reader.GetInt64(13),
                            PriceTickets = reader.IsDBNull(14) ? 0L : reader.GetInt64(14),
                            LimitedUnique = !reader.IsDBNull(15) && reader.GetBoolean(15),
                            LimitedQuantity = reader.IsDBNull(16) ? null : (long?)reader.GetInt64(16),
                            LimitedRemaining = reader.IsDBNull(17) ? null : (long?)reader.GetInt64(17),
                            LimitedUntil = reader.IsDBNull(18) ? null : (DateTime?)reader.GetDateTime(18),
                            AllowComments = reader.IsDBNull(19) || reader.GetBoolean(19),
                            Genre = reader.IsDBNull(20) ? 1 : reader.GetInt32(20),
                            IsPlace = !reader.IsDBNull(21) && reader.GetBoolean(21),
                            PrivacyLevel = reader.IsDBNull(22) ? 1 : reader.GetInt32(22),
                            CustomIcon = !reader.IsDBNull(23) && reader.GetBoolean(23),
                            PlaceCustomIconUrl = reader.IsDBNull(24) ? null : reader.GetString(24),
                            PlaceCustomIconHighResUrl = reader.IsDBNull(25) ? null : reader.GetString(25),
                            PlaceCustomIconHash = reader.IsDBNull(26) ? null : reader.GetString(26),
                            GeneratedIcon = !reader.IsDBNull(27) && reader.GetBoolean(27),
                            PlaceGeneratedIconUrl = reader.IsDBNull(28) ? null : reader.GetString(28),
                            PlaceGeneratedIconHighResUrl = reader.IsDBNull(29) ? null : reader.GetString(29),
                            PlaceGeneratedIconHash = reader.IsDBNull(30) ? null : reader.GetString(30),
                            PlaceAutoGeneratedThumbnail = !reader.IsDBNull(31) && reader.GetBoolean(31),
                            PlaceGeneratedThumbnailUrl = reader.IsDBNull(32) ? null : reader.GetString(32),
                            PlaceCustomThumbnail = !reader.IsDBNull(33) && reader.GetBoolean(33),
                            PlaceVideoThumbnail = !reader.IsDBNull(34) && reader.GetBoolean(34),
                            PlaceThumbnailVideo = reader.IsDBNull(35) ? null : reader.GetString(35),
                            MaxVisitorCount = reader.IsDBNull(36) ? 8 : reader.GetInt32(36),
                            DeviceCompatibility = reader.IsDBNull(37) ? "[1, 2, 3]" : reader.GetString(37),
                            ServerFillType = reader.IsDBNull(38) ? 0 : reader.GetInt32(38),
                            NumberOfCustomSocialSlots = reader.IsDBNull(39) ? 4 : reader.GetInt32(39),
                            AccessType = reader.IsDBNull(40) ? 1 : reader.GetInt32(40),
                            PrivateServersAllowed = reader.IsDBNull(41) ? true : reader.GetBoolean(41),
                            IsPrivateServersFree = reader.IsDBNull(42) ? true : reader.GetBoolean(42),
                            PrivateServersPrice = reader.IsDBNull(43) ? 100 : reader.GetInt32(43),
                            PaidAccessEnabled = reader.IsDBNull(44) ? false : reader.GetBoolean(44),
                            PaidAccessPrice = reader.IsDBNull(45) ? 0 : reader.GetInt32(45),
                            IsCopyingAllowed = reader.IsDBNull(46) ? false : reader.GetBoolean(46),
                            IsAllGenresAllowed = reader.IsDBNull(47) ? false : reader.GetBoolean(47),
                            AllowedGearTypes = reader.IsDBNull(48) ? "[]" : reader.GetString(48),
                            AllowPlaceToBeCopiedInGame = reader.IsDBNull(49) ? false : reader.GetBoolean(49),
                            AllowPlaceToBeUpdatedInGame = reader.IsDBNull(50) ? false : reader.GetBoolean(50),
                            RecentAveragePrice = reader.IsDBNull(51) ? 0 : reader.GetInt64(51)
                        };

                        return record;
                    }
                }
            }
        }

        public async Task<AssetRecord?> GetPlaceByIdAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using (var conn = new NpgsqlConnection(connectionString))
            {
                await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

                const string sql = @"select asset_id, name, asset_type_id, owner_user_id, content_hash, file_extension, content_type, thumbnail_url, high_res_thumbnail_url, description, asset_image, asset_link, on_sale, price, price_in_tix, limited_unique, limited_quantity, limited_remaining, limited_until, allow_comments, genre, is_place, privacy_level, custom_icon, place_custom_icon_url, place_custom_icon_high_res_url, place_custom_icon_hash, generated_icon, place_generated_icon_url, place_generated_icon_high_res_url, place_generated_icon_hash, place_autogenerated_thumbnail, place_generated_thumbnail_url, place_custom_thumbnail, place_video_thumbnail, place_thumbnail_video, max_visitor_count, device_compatibility, server_fill_type, number_of_custom_social_slots, access_type, private_servers_allowed, private_servers_free, private_servers_price, paid_access_enabled, paid_access_price, is_copying_allowed, is_all_genres_allowed, allowed_gear_types, allow_place_to_be_copied_in_game, allow_place_to_be_updated_in_game, recent_average_price
from assets
where asset_id = @id and is_place = true";

                using (var cmd = new NpgsqlCommand(sql, conn))
                {
                    cmd.Parameters.AddWithValue("id", assetId);

                    using (var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
                    {
                        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
                            return null;

                        var record = new AssetRecord
                        {
                            AssetId = reader.GetInt64(0),
                            Name = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            AssetTypeId = reader.IsDBNull(2) ? 0 : reader.GetInt32(2),
                            OwnerUserId = reader.IsDBNull(3) ? 0 : reader.GetInt64(3),
                            ContentHash = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                            FileExtension = reader.IsDBNull(5) ? null : reader.GetString(5),
                            ContentType = reader.IsDBNull(6) ? null : reader.GetString(6),
                            ThumbnailUrl = reader.IsDBNull(7) ? null : reader.GetString(7),
                            HighResThumbnailUrl = reader.IsDBNull(8) ? null : reader.GetString(8),
                            Description = reader.IsDBNull(9) ? null : reader.GetString(9),
                            AssetImage = !reader.IsDBNull(10) && reader.GetBoolean(10),
                            AssetLink = reader.IsDBNull(11) ? (long?)null : reader.GetInt64(11),
                            OnSale = !reader.IsDBNull(12) && reader.GetBoolean(12),
                            Price = reader.IsDBNull(13) ? 0L : reader.GetInt64(13),
                            PriceTickets = reader.IsDBNull(14) ? 0L : reader.GetInt64(14),
                            LimitedUnique = !reader.IsDBNull(15) && reader.GetBoolean(15),
                            LimitedQuantity = reader.IsDBNull(16) ? null : (long?)reader.GetInt64(16),
                            LimitedRemaining = reader.IsDBNull(17) ? null : (long?)reader.GetInt64(17),
                            LimitedUntil = reader.IsDBNull(18) ? null : (DateTime?)reader.GetDateTime(18),
                            AllowComments = reader.IsDBNull(19) || reader.GetBoolean(19),
                            Genre = reader.IsDBNull(20) ? 1 : reader.GetInt32(20),
                            IsPlace = !reader.IsDBNull(21) && reader.GetBoolean(21),
                            PrivacyLevel = reader.IsDBNull(22) ? 1 : reader.GetInt32(22),
                            CustomIcon = !reader.IsDBNull(23) && reader.GetBoolean(23),
                            PlaceCustomIconUrl = reader.IsDBNull(24) ? null : reader.GetString(24),
                            PlaceCustomIconHighResUrl = reader.IsDBNull(25) ? null : reader.GetString(25),
                            PlaceCustomIconHash = reader.IsDBNull(26) ? null : reader.GetString(26),
                            GeneratedIcon = !reader.IsDBNull(27) && reader.GetBoolean(27),
                            PlaceGeneratedIconUrl = reader.IsDBNull(28) ? null : reader.GetString(28),
                            PlaceGeneratedIconHighResUrl = reader.IsDBNull(29) ? null : reader.GetString(29),
                            PlaceGeneratedIconHash = reader.IsDBNull(30) ? null : reader.GetString(30),
                            PlaceAutoGeneratedThumbnail = !reader.IsDBNull(31) && reader.GetBoolean(31),
                            PlaceGeneratedThumbnailUrl = reader.IsDBNull(32) ? null : reader.GetString(32),
                            PlaceCustomThumbnail = !reader.IsDBNull(33) && reader.GetBoolean(33),
                            PlaceVideoThumbnail = !reader.IsDBNull(34) && reader.GetBoolean(34),
                            PlaceThumbnailVideo = reader.IsDBNull(35) ? null : reader.GetString(35),
                            MaxVisitorCount = reader.IsDBNull(36) ? 8 : reader.GetInt32(36),
                            DeviceCompatibility = reader.IsDBNull(37) ? "[1, 2, 3]" : reader.GetString(37),
                            ServerFillType = reader.IsDBNull(38) ? 0 : reader.GetInt32(38),
                            NumberOfCustomSocialSlots = reader.IsDBNull(39) ? 4 : reader.GetInt32(39),
                            AccessType = reader.IsDBNull(40) ? 1 : reader.GetInt32(40),
                            PrivateServersAllowed = reader.IsDBNull(41) ? true : reader.GetBoolean(41),
                            IsPrivateServersFree = reader.IsDBNull(42) ? true : reader.GetBoolean(42),
                            PrivateServersPrice = reader.IsDBNull(43) ? 100 : reader.GetInt32(43),
                            PaidAccessEnabled = reader.IsDBNull(44) ? false : reader.GetBoolean(44),
                            PaidAccessPrice = reader.IsDBNull(45) ? 0 : reader.GetInt32(45),
                            IsCopyingAllowed = reader.IsDBNull(46) ? false : reader.GetBoolean(46),
                            IsAllGenresAllowed = reader.IsDBNull(47) ? false : reader.GetBoolean(47),
                            AllowedGearTypes = reader.IsDBNull(48) ? "[]" : reader.GetString(48),
                            AllowPlaceToBeCopiedInGame = reader.IsDBNull(49) ? false : reader.GetBoolean(49),
                            AllowPlaceToBeUpdatedInGame = reader.IsDBNull(50) ? false : reader.GetBoolean(50),
                            RecentAveragePrice = reader.IsDBNull(51) ? 0 : reader.GetInt64(51)
                        };

                        return record;
                    }
                }
            }
        }
    }
}
