using System;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;

namespace Assets
{
    public sealed class AssetRecord
    {
        public long AssetId { get; set; }
        public string Name { get; set; } = string.Empty;
        public int AssetTypeId { get; set; }
        public long OwnerUserId { get; set; }
        public string ContentHash { get; set; } = string.Empty;
        public string? FileExtension { get; set; }
        public string? ContentType { get; set; }
        public string? ThumbnailUrl { get; set; }
        public string? HighResThumbnailUrl { get; set; }
        public string? Description { get; set; }
        public bool AssetImage { get; set; }
        public long? AssetLink { get; set; }
        public bool OnSale { get; set; }
        public long Price { get; set; }
        public bool AllowComments { get; set; }
        public int Genre { get; set; }
        public bool IsPlace { get; set; }
        public int PrivacyLevel { get; set; }
        public bool CustomIcon { get; set; }
        public string? PlaceCustomIconUrl { get; set; }
        public string? PlaceCustomIconHighResUrl { get; set; }
        public string? PlaceCustomIconHash { get; set; }
        public bool GeneratedIcon { get; set; }
        public string? PlaceGeneratedIconUrl { get; set; }
        public string? PlaceGeneratedIconHighResUrl { get; set; }
        public string? PlaceGeneratedIconHash { get; set; }
        public bool PlaceAutoGeneratedThumbnail { get; set; }
        public string? PlaceGeneratedThumbnailUrl { get; set; }
        public bool PlaceCustomThumbnail { get; set; }
        public bool PlaceVideoThumbnail { get; set; }
        public string? PlaceThumbnailVideo { get; set; }
        public int MaxVisitorCount { get; set; } = 8;
        public string? DeviceCompatibility { get; set; } = "[1, 2, 3]";
        public int ServerFillType { get; set; } = 0;
        public int NumberOfCustomSocialSlots { get; set; } = 4;
        public int AccessType { get; set; } = 1; // 1 = Everyone, 2 = Friends
        public bool PrivateServersAllowed { get; set; } = true; // Private servers allowed setting
        public bool IsPrivateServersFree { get; set; } = true; // Private servers free setting
        public int PrivateServersPrice { get; set; } = 100; // Private servers price setting
        public bool PaidAccessEnabled { get; set; } = false; // Paid access enabled setting
        public int PaidAccessPrice { get; set; } = 0; // Paid access price setting
        public bool IsCopyingAllowed { get; set; } = false; // Allow copying setting
        public bool IsAllGenresAllowed { get; set; } = false; // Allow all genres setting
        public string? AllowedGearTypes { get; set; } = "[]"; // Allowed gear types JSON array
        public bool AllowPlaceToBeCopiedInGame { get; set; } = false; // Allow place to be copied in game
        public bool AllowPlaceToBeUpdatedInGame { get; set; } = false; // Allow place to be updated in game
    }

    public sealed class AssetCreateParams
    {
        public string Name { get; set; } = string.Empty;
        public int AssetTypeId { get; set; }
        public long OwnerUserId { get; set; }
        public string ContentHash { get; set; } = string.Empty;
        public string? FileExtension { get; set; }
        public string? ContentType { get; set; }
        public string? ThumbnailUrl { get; set; }
        public string? HighResThumbnailUrl { get; set; }
        public string? Description { get; set; }
        public bool AssetImage { get; set; }
        public long? AssetLink { get; set; }
        public bool CustomIcon { get; set; }
        public string? PlaceCustomIconUrl { get; set; }
        public string? PlaceCustomIconHighResUrl { get; set; }
        public string? PlaceCustomIconHash { get; set; }
        public bool GeneratedIcon { get; set; }
        public string? PlaceGeneratedIconUrl { get; set; }
        public string? PlaceGeneratedIconHighResUrl { get; set; }
        public string? PlaceGeneratedIconHash { get; set; }
        public bool PlaceAutoGeneratedThumbnail { get; set; }
        public string? PlaceGeneratedThumbnailUrl { get; set; }
        public bool PlaceCustomThumbnail { get; set; }
        public bool PlaceVideoThumbnail { get; set; }
        public string? PlaceThumbnailVideo { get; set; }
        public int MaxVisitorCount { get; set; } = 8;
        public string? DeviceCompatibility { get; set; } = "[1, 2, 3]";
        public int ServerFillType { get; set; } = 0;
        public int NumberOfCustomSocialSlots { get; set; } = 4;
        public int AccessType { get; set; } = 1; // 1 = Everyone, 2 = Friends
        public bool PrivateServersAllowed { get; set; } = true; // Private servers allowed setting
        public bool IsPrivateServersFree { get; set; } = true; // Private servers free setting
        public int PrivateServersPrice { get; set; } = 100; // Private servers price setting
        public bool PaidAccessEnabled { get; set; } = false; // Paid access enabled setting
        public int PaidAccessPrice { get; set; } = 0; // Paid access price setting
        public bool IsCopyingAllowed { get; set; } = false; // Allow copying setting
        public bool IsPlace { get; set; } = false; // Whether this asset is a place
        public bool InUniverse { get; set; } = false; // Whether this place is in a universe
        public bool AllowPlaceToBeUpdatedInGame { get; set; } = false; // Allow place to be updated in game
    }

    public sealed class AssetsRepository
    {
        public async Task<long> CreateAssetAsync(string connectionString, AssetCreateParams p, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (p == null)
                throw new ArgumentNullException(nameof(p));

            if (string.IsNullOrWhiteSpace(p.Description))
            {
                if (p.AssetTypeId == 2)
                {
                    p.Description = "T-shirt";
                }
                else
                {
                    var label = AssetTypeNames.GetConfigureLabel(p.AssetTypeId);
                    if (!string.IsNullOrWhiteSpace(label))
                        p.Description = label;
                }
            }

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"insert into assets (
    name,
    asset_type_id,
    owner_user_id,
    content_hash,
    file_extension,
    content_type,
    thumbnail_url,
    high_res_thumbnail_url,
    description,
    asset_image,
    asset_link,
    custom_icon,
    place_custom_icon_url,
    place_custom_icon_hash,
    generated_icon,
    place_generated_icon_url,
    place_generated_icon_hash,
    is_place,
    in_universe
) values (
    @name,
    @asset_type_id,
    @owner_user_id,
    @content_hash,
    @file_extension,
    @content_type,
    @thumbnail_url,
    @high_res_thumbnail_url,
    @description,
    @asset_image,
    @asset_link,
    @custom_icon,
    @place_custom_icon_url,
    @place_custom_icon_hash,
    @generated_icon,
    @place_generated_icon_url,
    @place_generated_icon_hash,
    @is_place,
    @in_universe
) returning asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("name", p.Name);
            cmd.Parameters.AddWithValue("asset_type_id", p.AssetTypeId);
            cmd.Parameters.AddWithValue("owner_user_id", p.OwnerUserId);
            cmd.Parameters.AddWithValue("content_hash", p.ContentHash);
            cmd.Parameters.AddWithValue("file_extension", (object?)p.FileExtension ?? DBNull.Value);
            cmd.Parameters.AddWithValue("content_type", (object?)p.ContentType ?? DBNull.Value);
            cmd.Parameters.AddWithValue("thumbnail_url", (object?)p.ThumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("high_res_thumbnail_url", (object?)p.HighResThumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("description", (object?)p.Description ?? DBNull.Value);
            cmd.Parameters.AddWithValue("asset_image", p.AssetImage);
            cmd.Parameters.AddWithValue("asset_link", (object?)p.AssetLink ?? DBNull.Value);
            cmd.Parameters.AddWithValue("custom_icon", p.CustomIcon);
            cmd.Parameters.AddWithValue("place_custom_icon_url", (object?)p.PlaceCustomIconUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("place_custom_icon_hash", (object?)p.PlaceCustomIconHash ?? DBNull.Value);
            cmd.Parameters.AddWithValue("generated_icon", p.GeneratedIcon);
            cmd.Parameters.AddWithValue("place_generated_icon_url", (object?)p.PlaceGeneratedIconUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("place_generated_icon_hash", (object?)p.PlaceGeneratedIconHash ?? DBNull.Value);
            cmd.Parameters.AddWithValue("is_place", p.IsPlace);
            cmd.Parameters.AddWithValue("in_universe", p.InUniverse);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result == null || result == DBNull.Value)
                throw new InvalidOperationException("Failed to insert asset record.");

            return Convert.ToInt64(result);
        }

        public async Task UpdateAssetImageLinkAsync(string connectionString, long assetId, bool assetImage, long? assetLink, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set asset_image = @asset_image,
    asset_link = @asset_link
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("asset_image", assetImage);
            cmd.Parameters.AddWithValue("asset_link", (object?)assetLink ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetMetadataAsync(string connectionString, long assetId, string name, string? description, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("name is required", nameof(name));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set name = @name,
    description = @description,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("name", name);
            cmd.Parameters.AddWithValue("description", (object?)description ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetSaleAsync(string connectionString, long assetId, bool onSale, long price, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (price < 0)
                throw new ArgumentOutOfRangeException(nameof(price));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set on_sale = @on_sale,
    price = @price,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("on_sale", onSale);
            cmd.Parameters.AddWithValue("price", price);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetAllowCommentsAsync(string connectionString, long assetId, bool allowComments, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set allow_comments = @allow_comments,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("allow_comments", allowComments);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetMaxVisitorCountAsync(string connectionString, long assetId, int maxVisitorCount, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (maxVisitorCount < 1 || maxVisitorCount > 100)
                throw new ArgumentOutOfRangeException(nameof(maxVisitorCount), "Max visitor count must be between 1 and 100");

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set max_visitor_count = @max_visitor_count,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("max_visitor_count", maxVisitorCount);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetGenreAsync(string connectionString, long assetId, int genre, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (genre < 0 || genre > 20)
                throw new ArgumentOutOfRangeException(nameof(genre));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set genre = @genre,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("genre", genre);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetThumbnailsAsync(string connectionString, long assetId, string? thumbnailUrl, string? highResThumbnailUrl, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set thumbnail_url = @thumbnail_url,
    high_res_thumbnail_url = @high_res_thumbnail_url,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("thumbnail_url", (object?)thumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("high_res_thumbnail_url", (object?)highResThumbnailUrl ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task AddFavoriteAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set favorites = case
    when exists (
        select 1
        from jsonb_array_elements_text(favorites) as x(v)
        where v = @user_id::text
    ) then favorites
    else favorites || to_jsonb(@user_id::bigint)
end,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<bool> UserHasFavoritedAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select exists (
    select 1
    from assets
    where asset_id = @asset_id
      and exists (
          select 1
          from jsonb_array_elements_text(favorites) as x(v)
          where v = @user_id::text
      )
);";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result is bool b)
                return b;

            return false;
        }

        public async Task RemoveFavoriteAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set favorites = coalesce(
    (
        select jsonb_agg(value::bigint)
        from jsonb_array_elements(favorites) as value
        where value::text <> @user_id::text
    ),
    '[]'::jsonb
),
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<int> GetFavoriteCountAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select coalesce(jsonb_array_length(favorites), 0)
from assets
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result is int i)
                return i;
            if (result is long l)
                return (int)Math.Min(l, int.MaxValue);

            return 0;
        }

        public static async Task<(DateTime CreatedAt, DateTime UpdatedAt, int MaxPlayers, int Genre, bool IsAllGenresAllowed, string AllowedGearTypes, bool PrivateServersAllowed, bool PrivateServersFree, int PrivateServersPrice)?> GetPlaceAdditionalDataAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select created_at, last_updated, max_visitor_count, genre, is_all_genres_allowed, allowed_gear_types,
private_servers_allowed, private_servers_free, private_servers_price
from assets
where asset_id = @id and is_place = true";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("id", assetId);

            using var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                return (
                    reader.GetDateTime(0),
                    reader.GetDateTime(1),
                    reader.IsDBNull(2) ? 8 : reader.GetInt32(2),
                    reader.IsDBNull(3) ? 1 : reader.GetInt32(3),
                    reader.IsDBNull(4) ? (bool)reader.GetBoolean(4) : false,
                    reader.IsDBNull(5) ? "[]" : reader.GetString(5),
                    reader.IsDBNull(6) ? false : reader.GetBoolean(6),
                    reader.IsDBNull(7) ? false : reader.GetBoolean(7),
                    reader.IsDBNull(8) ? 0 : reader.GetInt32(8)
                );
            }

            return null;
        }

        }
}
