using System;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;

namespace Assets
{
    public sealed class AssetRecord
    {
        public long AssetId { get; set; }
        public string Name { get; set; } = string.Empty;
        public int AssetTypeId { get; set; }
        public long OwnerUserId { get; set; }
        public string ContentHash { get; set; } = string.Empty;
        public string? FileExtension { get; set; }
        public string? ContentType { get; set; }
        public string? ThumbnailUrl { get; set; }
        public string? HighResThumbnailUrl { get; set; }
        public string? Description { get; set; }
        public bool AssetImage { get; set; }
        public long? AssetLink { get; set; }
        public bool OnSale { get; set; }
        public long Price { get; set; }
        public long PriceTickets { get; set; }
        public bool LimitedUnique { get; set; }
        public long? LimitedQuantity { get; set; }
        public long? LimitedRemaining { get; set; }
        public DateTime? LimitedUntil { get; set; }
        public bool AllowComments { get; set; }
        public int Genre { get; set; }
        public bool IsPlace { get; set; }
        public int PrivacyLevel { get; set; }
        public bool CustomIcon { get; set; }
        public string? PlaceCustomIconUrl { get; set; }
        public string? PlaceCustomIconHighResUrl { get; set; }
        public string? PlaceCustomIconHash { get; set; }
        public bool GeneratedIcon { get; set; }
        public string? PlaceGeneratedIconUrl { get; set; }
        public string? PlaceGeneratedIconHighResUrl { get; set; }
        public string? PlaceGeneratedIconHash { get; set; }
        public bool PlaceAutoGeneratedThumbnail { get; set; }
        public string? PlaceGeneratedThumbnailUrl { get; set; }
        public bool PlaceCustomThumbnail { get; set; }
        public bool PlaceVideoThumbnail { get; set; }
        public string? PlaceThumbnailVideo { get; set; }
        public int MaxVisitorCount { get; set; } = 8;
        public string? DeviceCompatibility { get; set; } = "[1, 2, 3]";
        public int ServerFillType { get; set; } = 0;
        public int NumberOfCustomSocialSlots { get; set; } = 4;
        public int AccessType { get; set; } = 1; // 1 = Everyone, 2 = Friends
        public bool PrivateServersAllowed { get; set; } = true; // Private servers allowed setting
        public bool IsPrivateServersFree { get; set; } = true; // Private servers free setting
        public int PrivateServersPrice { get; set; } = 100; // Private servers price setting
        public bool PaidAccessEnabled { get; set; } = false; // Paid access enabled setting
        public int PaidAccessPrice { get; set; } = 0; // Paid access price setting
        public bool IsCopyingAllowed { get; set; } = false; // Allow copying setting
        public bool IsAllGenresAllowed { get; set; } = false; // Allow all genres setting
        public string? AllowedGearTypes { get; set; } = "[]"; // Allowed gear types JSON array
        public bool AllowPlaceToBeCopiedInGame { get; set; } = false; // Allow place to be copied in game
        public bool AllowPlaceToBeUpdatedInGame { get; set; } = false; // Allow place to be updated in game
        public long RecentAveragePrice { get; set; }
    }

    public sealed class AssetCreateParams
    {
        public string Name { get; set; } = string.Empty;
        public int AssetTypeId { get; set; }
        public long OwnerUserId { get; set; }
        public string ContentHash { get; set; } = string.Empty;
        public string? FileExtension { get; set; }
        public string? ContentType { get; set; }
        public string? ThumbnailUrl { get; set; }
        public string? HighResThumbnailUrl { get; set; }
        public string? Description { get; set; }
        public bool AssetImage { get; set; }
        public long? AssetLink { get; set; }
        public bool LimitedUnique { get; set; }
        public long? LimitedQuantity { get; set; }
        public long? LimitedRemaining { get; set; }
        public DateTime? LimitedUntil { get; set; }
        public bool CustomIcon { get; set; }
        public string? PlaceCustomIconUrl { get; set; }
        public string? PlaceCustomIconHighResUrl { get; set; }
        public string? PlaceCustomIconHash { get; set; }
        public bool GeneratedIcon { get; set; }
        public string? PlaceGeneratedIconUrl { get; set; }
        public string? PlaceGeneratedIconHighResUrl { get; set; }
        public string? PlaceGeneratedIconHash { get; set; }
        public bool PlaceAutoGeneratedThumbnail { get; set; }
        public string? PlaceGeneratedThumbnailUrl { get; set; }
        public bool PlaceCustomThumbnail { get; set; }
        public bool PlaceVideoThumbnail { get; set; }
        public string? PlaceThumbnailVideo { get; set; }
        public int MaxVisitorCount { get; set; } = 8;
        public string? DeviceCompatibility { get; set; } = "[1, 2, 3]";
        public int ServerFillType { get; set; } = 0;
        public int NumberOfCustomSocialSlots { get; set; } = 4;
        public int AccessType { get; set; } = 1; // 1 = Everyone, 2 = Friends
        public bool PrivateServersAllowed { get; set; } = true; // Private servers allowed setting
        public bool IsPrivateServersFree { get; set; } = true; // Private servers free setting
        public int PrivateServersPrice { get; set; } = 100; // Private servers price setting
        public bool PaidAccessEnabled { get; set; } = false; // Paid access enabled setting
        public int PaidAccessPrice { get; set; } = 0; // Paid access price setting
        public bool IsCopyingAllowed { get; set; } = false; // Allow copying setting
        public bool IsPlace { get; set; } = false; // Whether this asset is a place
        public bool InUniverse { get; set; } = false; // Whether this place is in a universe
        public long? BelongsToUniverse { get; set; } // Universe this asset belongs to (game passes)
        public bool AllowPlaceToBeUpdatedInGame { get; set; } = false; // Allow place to be updated in game
    }

    public sealed class AssetsRepository
    {
        public async Task<bool> AssetExistsAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select exists(select 1 from assets where asset_id = @asset_id);";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            return result is bool exists && exists;
        }

        public async Task<long> ChangeAssetIdAsync(string connectionString, long currentAssetId, long newAssetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (currentAssetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(currentAssetId));
            if (newAssetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(newAssetId));

            // Add debugging
            System.Diagnostics.Debug.WriteLine($"[DEBUG] AssetsRepository.ChangeAssetIdAsync: currentAssetId={currentAssetId}, newAssetId={newAssetId}");

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            // Check if the new asset ID already exists
            const string checkSql = @"select exists(select 1 from assets where asset_id = @new_asset_id);";
            using var checkCmd = new NpgsqlCommand(checkSql, conn);
            checkCmd.Parameters.AddWithValue("new_asset_id", newAssetId);
            
            var existsResult = await checkCmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (existsResult is bool exists && exists)
            {
                System.Diagnostics.Debug.WriteLine($"[DEBUG] Asset ID {newAssetId} already exists, throwing exception");
                throw new InvalidOperationException($"Asset ID {newAssetId} already exists. Cannot overwrite existing asset.");
            }

            // Check if the current asset exists
            const string currentCheckSql = @"select exists(select 1 from assets where asset_id = @current_asset_id);";
            using var currentCheckCmd = new NpgsqlCommand(currentCheckSql, conn);
            currentCheckCmd.Parameters.AddWithValue("current_asset_id", currentAssetId);
            
            var currentExistsResult = await currentCheckCmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (currentExistsResult is bool currentExists && !currentExists)
            {
                throw new InvalidOperationException($"Asset ID {currentAssetId} does not exist.");
            }

            // Change the asset ID
            const string updateSql = @"alter table assets alter column asset_id set data type bigint;
                alter sequence assets_asset_id_seq restart with @new_asset_id;
                update assets set asset_id = @new_asset_id where asset_id = @current_asset_id;
                alter table assets alter column asset_id set default nextval('assets_asset_id_seq');";

            // Add debugging before sequence manipulation
            System.Diagnostics.Debug.WriteLine($"[DEBUG] About to execute sequence manipulation SQL");
            System.Diagnostics.Debug.WriteLine($"[DEBUG] SQL: {updateSql}");
            System.Diagnostics.Debug.WriteLine($"[DEBUG] Parameters: new_asset_id={newAssetId}, current_asset_id={currentAssetId}");

            using var cmd = new NpgsqlCommand(updateSql, conn);
            cmd.Parameters.AddWithValue("new_asset_id", newAssetId);
            cmd.Parameters.AddWithValue("current_asset_id", currentAssetId);

            var rowsAffected = await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            System.Diagnostics.Debug.WriteLine($"[DEBUG] ChangeAssetIdAsync: rowsAffected={rowsAffected}");
            
            return newAssetId;
        }

        public async Task<long> CreateAssetAsync(string connectionString, AssetCreateParams p, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (p == null)
                throw new ArgumentNullException(nameof(p));

            if (string.IsNullOrWhiteSpace(p.Description))
            {
                if (p.AssetTypeId == 2)
                {
                    p.Description = "T-shirt";
                }
                else if (p.AssetTypeId == 10)
                {
                    p.Description = "Model";
                }
                else if (p.AssetTypeId == 4)
                {
                    p.Description = "Mesh";
                }
                else
                {
                    var label = AssetTypeNames.GetConfigureLabel(p.AssetTypeId);
                    if (!string.IsNullOrWhiteSpace(label))
                        p.Description = label;
                }
            }

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"insert into assets (
    name,
    asset_type_id,
    owner_user_id,
    content_hash,
    file_extension,
    content_type,
    thumbnail_url,
    high_res_thumbnail_url,
    description,
    asset_image,
    asset_link,
    limited_unique,
    limited_quantity,
    limited_remaining,
    limited_until,
    custom_icon,
    place_custom_icon_url,
    place_custom_icon_hash,
    generated_icon,
    place_generated_icon_url,
    place_generated_icon_hash,
    is_place,
    in_universe,
    is_copying_allowed,
    belongs_to_universe
) values (
    @name,
    @asset_type_id,
    @owner_user_id,
    @content_hash,
    @file_extension,
    @content_type,
    @thumbnail_url,
    @high_res_thumbnail_url,
    @description,
    @asset_image,
    @asset_link,
    @limited_unique,
    @limited_quantity,
    @limited_remaining,
    @limited_until,
    @custom_icon,
    @place_custom_icon_url,
    @place_custom_icon_hash,
    @generated_icon,
    @place_generated_icon_url,
    @place_generated_icon_hash,
    @is_place,
    @in_universe,
    @is_copying_allowed,
    @belongs_to_universe
) returning asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("name", p.Name);
            cmd.Parameters.AddWithValue("asset_type_id", p.AssetTypeId);
            cmd.Parameters.AddWithValue("owner_user_id", p.OwnerUserId);
            cmd.Parameters.AddWithValue("content_hash", p.ContentHash);
            cmd.Parameters.AddWithValue("file_extension", (object?)p.FileExtension ?? DBNull.Value);
            cmd.Parameters.AddWithValue("content_type", (object?)p.ContentType ?? DBNull.Value);
            cmd.Parameters.AddWithValue("thumbnail_url", (object?)p.ThumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("high_res_thumbnail_url", (object?)p.HighResThumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("description", (object?)p.Description ?? DBNull.Value);
            cmd.Parameters.AddWithValue("asset_image", p.AssetImage);
            cmd.Parameters.AddWithValue("asset_link", (object?)p.AssetLink ?? DBNull.Value);
            cmd.Parameters.AddWithValue("limited_unique", p.LimitedUnique);
            cmd.Parameters.AddWithValue("limited_quantity", (object?)p.LimitedQuantity ?? DBNull.Value);
            cmd.Parameters.AddWithValue("limited_remaining", (object?)p.LimitedRemaining ?? DBNull.Value);
            cmd.Parameters.AddWithValue("limited_until", (object?)p.LimitedUntil ?? DBNull.Value);
            cmd.Parameters.AddWithValue("custom_icon", p.CustomIcon);
            cmd.Parameters.AddWithValue("place_custom_icon_url", (object?)p.PlaceCustomIconUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("place_custom_icon_hash", (object?)p.PlaceCustomIconHash ?? DBNull.Value);
            cmd.Parameters.AddWithValue("generated_icon", p.GeneratedIcon);
            cmd.Parameters.AddWithValue("place_generated_icon_url", (object?)p.PlaceGeneratedIconUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("place_generated_icon_hash", (object?)p.PlaceGeneratedIconHash ?? DBNull.Value);
            cmd.Parameters.AddWithValue("is_place", p.IsPlace);
            cmd.Parameters.AddWithValue("in_universe", p.InUniverse);
            cmd.Parameters.AddWithValue("is_copying_allowed", p.IsCopyingAllowed);
            cmd.Parameters.AddWithValue("belongs_to_universe", (object?)p.BelongsToUniverse ?? DBNull.Value);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result == null || result == DBNull.Value)
                throw new InvalidOperationException("Failed to insert asset record.");

            var assetId = Convert.ToInt64(result);

            if (!string.IsNullOrWhiteSpace(p.ContentHash))
            {
                await AppendVersionHistoryAsync(connectionString, assetId, p.ContentHash, cancellationToken).ConfigureAwait(false);
            }

            return assetId;
        }

        public async Task UpdateAssetImageLinkAsync(string connectionString, long assetId, bool assetImage, long? assetLink, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set asset_image = @asset_image,
    asset_link = @asset_link
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("asset_image", assetImage);
            cmd.Parameters.AddWithValue("asset_link", (object?)assetLink ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetMetadataAsync(string connectionString, long assetId, string name, string? description, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException("name is required", nameof(name));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set name = @name,
    description = @description,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("name", name);
            cmd.Parameters.AddWithValue("description", (object?)description ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetPricesAsync(string connectionString, long assetId, long robuxPrice, long tixPrice, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            {
                await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

                const string sql = @"update assets
set price = @price,
    price_in_tix = @price_in_tix,
    on_sale = true,
    last_updated = now()
where asset_id = @asset_id";

                using var cmd = new NpgsqlCommand(sql, conn);
                {
                    cmd.Parameters.AddWithValue("asset_id", assetId);
                    cmd.Parameters.AddWithValue("price", robuxPrice);
                    cmd.Parameters.AddWithValue("price_in_tix", tixPrice);

                    await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
                }
            }
        }

        public async Task UpdateAssetSaleAsync(string connectionString, long assetId, bool onSale, long price, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (price < 0)
                throw new ArgumentOutOfRangeException(nameof(price));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set on_sale = @on_sale,
    price = @price,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("on_sale", onSale);
            cmd.Parameters.AddWithValue("price", price);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetAllowCommentsAsync(string connectionString, long assetId, bool allowComments, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set allow_comments = @allow_comments,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("allow_comments", allowComments);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetCopyingAllowedAsync(string connectionString, long assetId, bool isCopyingAllowed, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set is_copying_allowed = @is_copying_allowed,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("is_copying_allowed", isCopyingAllowed);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetContentHashAsync(string connectionString, long assetId, string contentHash, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (string.IsNullOrWhiteSpace(contentHash))
                throw new ArgumentException("contentHash is required", nameof(contentHash));

            var oldHash = await GetContentHashAsync(connectionString, assetId, cancellationToken).ConfigureAwait(false);
            if (!string.IsNullOrWhiteSpace(oldHash))
            {
                await AppendVersionHistoryAsync(connectionString, assetId, oldHash, cancellationToken).ConfigureAwait(false);
            }

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set content_hash = @content_hash,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("content_hash", contentHash);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetModelContentAsync(string connectionString, long assetId, string newHash, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (string.IsNullOrWhiteSpace(newHash))
                throw new ArgumentException("newHash is required", nameof(newHash));

            var oldHash = await GetContentHashAsync(connectionString, assetId, cancellationToken).ConfigureAwait(false);
            if (!string.IsNullOrWhiteSpace(oldHash))
            {
                await AppendVersionHistoryAsync(connectionString, assetId, oldHash, cancellationToken).ConfigureAwait(false);
            }

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"UPDATE assets
                                 SET content_hash = @hash,
                                     file_extension = '.rbxm',
                                     content_type = 'application/octet-stream',
                                     last_updated = CURRENT_TIMESTAMP
                                 WHERE asset_id = @id";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("hash", newHash);
            cmd.Parameters.AddWithValue("id", assetId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<string?> GetContentHashAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"SELECT content_hash FROM assets WHERE asset_id = @asset_id";
            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result == null || result == DBNull.Value)
                return null;

            return Convert.ToString(result);
        }

        public async Task AppendVersionHistoryAsync(string connectionString, long assetId, string fileHash, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(fileHash))
                return;
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            var now = DateTime.Now.ToString("M/d/yyyy h:mm:ss tt");

            const string sql = @"
UPDATE assets
SET place_version_history = COALESCE(place_version_history, '[]'::jsonb) ||
    jsonb_build_object(
        'Version', (SELECT COALESCE(MAX((elem->>'Version')::int), 0) + 1 FROM jsonb_array_elements(COALESCE(place_version_history, '[]'::jsonb)) elem),
        'Date', @date,
        'File_Hash', @fileHash
    )
WHERE asset_id = @asset_id";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("date", now);
            cmd.Parameters.AddWithValue("fileHash", fileHash);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetMaxVisitorCountAsync(string connectionString, long assetId, int maxVisitorCount, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (maxVisitorCount < 1 || maxVisitorCount > 100)
                throw new ArgumentOutOfRangeException(nameof(maxVisitorCount), "Max visitor count must be between 1 and 100");

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set max_visitor_count = @max_visitor_count,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("max_visitor_count", maxVisitorCount);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetGenreAsync(string connectionString, long assetId, int genre, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (genre < 0 || genre > 20)
                throw new ArgumentOutOfRangeException(nameof(genre));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set genre = @genre,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("genre", genre);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task UpdateAssetThumbnailsAsync(string connectionString, long assetId, string? thumbnailUrl, string? highResThumbnailUrl, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set thumbnail_url = @thumbnail_url,
    high_res_thumbnail_url = @high_res_thumbnail_url
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("thumbnail_url", (object?)thumbnailUrl ?? DBNull.Value);
            cmd.Parameters.AddWithValue("high_res_thumbnail_url", (object?)highResThumbnailUrl ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task AddFavoriteAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set favorites = case
    when exists (
        select 1
        from jsonb_array_elements_text(favorites) as x(v)
        where v = @user_id::text
    ) then favorites
    else favorites || to_jsonb(@user_id::bigint)
end,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<bool> UserHasFavoritedAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select exists (
    select 1
    from assets
    where asset_id = @asset_id
      and exists (
          select 1
          from jsonb_array_elements_text(favorites) as x(v)
          where v = @user_id::text
      )
);";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result is bool b)
                return b;

            return false;
        }

        public async Task RemoveFavoriteAsync(string connectionString, long userId, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (userId <= 0)
                throw new ArgumentOutOfRangeException(nameof(userId));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set favorites = coalesce(
    (
        select jsonb_agg(value::bigint)
        from jsonb_array_elements(favorites) as value
        where value::text <> @user_id::text
    ),
    '[]'::jsonb
),
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("user_id", userId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<int> GetFavoriteCountAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select coalesce(jsonb_array_length(favorites), 0)
from assets
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            if (result is int i)
                return i;
            if (result is long l)
                return (int)Math.Min(l, int.MaxValue);

            return 0;
        }

        public static async Task<(DateTime CreatedAt, DateTime UpdatedAt, int MaxPlayers, int Genre, bool IsAllGenresAllowed, string AllowedGearTypes, bool PrivateServersAllowed, bool PrivateServersFree, int PrivateServersPrice)?> GetPlaceAdditionalDataAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select created_at, last_updated, max_visitor_count, genre, is_all_genres_allowed, allowed_gear_types,
private_servers_allowed, private_servers_free, private_servers_price
from assets
where asset_id = @id and is_place = true";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("id", assetId);

            using var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                return (
                    reader.GetDateTime(0),
                    reader.GetDateTime(1),
                    reader.IsDBNull(2) ? 8 : reader.GetInt32(2),
                    reader.IsDBNull(3) ? 1 : reader.GetInt32(3),
                    reader.IsDBNull(4) ? (bool)reader.GetBoolean(4) : false,
                    reader.IsDBNull(5) ? "[]" : reader.GetString(5),
                    reader.IsDBNull(6) ? false : reader.GetBoolean(6),
                    reader.IsDBNull(7) ? false : reader.GetBoolean(7),
                    reader.IsDBNull(8) ? 0 : reader.GetInt32(8)
                );
            }

            return null;
        }

        public async Task UpdateAssetLimitedAsync(string connectionString, long assetId, bool limitedUnique, long? limitedQuantity, long? limitedRemaining, DateTime? limitedUntil, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set limited_unique = @limited_unique,
    limited_quantity = @limited_quantity,
    limited_remaining = @limited_remaining,
    limited_until = @limited_until,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("limited_unique", limitedUnique);
            cmd.Parameters.AddWithValue("limited_quantity", (object?)limitedQuantity ?? DBNull.Value);
            cmd.Parameters.AddWithValue("limited_remaining", (object?)limitedRemaining ?? DBNull.Value);
            cmd.Parameters.AddWithValue("limited_until", (object?)limitedUntil ?? DBNull.Value);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task DecrementLimitedRemainingAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set limited_remaining = greatest(limited_remaining - 1, 0),
    last_updated = now()
where asset_id = @asset_id
  and limited_unique = true
  and limited_remaining > 0;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var rowsAffected = await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
            if (rowsAffected == 0)
                throw new InvalidOperationException("Asset not found or not a limited item with remaining stock.");
        }

        public static async Task<(bool LimitedUnique, long? LimitedQuantity, long? LimitedRemaining, DateTime? LimitedUntil)?> GetLimitedItemDataAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select limited_unique, limited_quantity, limited_remaining, limited_until
from assets
where asset_id = @id";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("id", assetId);

            await using var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
            if (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                return (
                    reader.GetBoolean(0),
                    reader.IsDBNull(1) ? null : reader.GetInt64(1),
                    reader.IsDBNull(2) ? null : reader.GetInt64(2),
                    reader.IsDBNull(3) ? null : reader.GetDateTime(3)
                );
            }

            return null;
        }

        /// <summary>
        /// Gets the creator user ID (owner) for a given asset ID
        /// </summary>
        /// <param name="connectionString">Database connection string</param>
        /// <param name="assetId">Asset ID to look up</param>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Creator user ID if found, null otherwise</returns>
        public static async Task<long?> GetAssetCreatorIdAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"SELECT owner_user_id 
                               FROM assets 
                               WHERE asset_id = @assetId";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("assetId", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            
            if (result == null || result == DBNull.Value)
                return null;
                
            return Convert.ToInt64(result);
        }

        /// <summary>
        /// Updates the featured rank of an asset (0 = not featured, 1-4 = featured slot).
        /// </summary>
        public async Task UpdateAssetFeaturedRankAsync(string connectionString, long assetId, int rank, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));
            if (rank < 0 || rank > 4)
                throw new ArgumentOutOfRangeException(nameof(rank), "Rank must be between 0 and 4.");

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets
set featured_rank = @rank,
    last_updated = now()
where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);
            cmd.Parameters.AddWithValue("rank", rank);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        public async Task<bool> BadgeExistsAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select exists(select 1 from assets where asset_id = @asset_id and asset_type_id = 21);";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            var result = await cmd.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false);
            return result is bool exists && exists;
        }

        public async Task IncrementAssetSalesAsync(string connectionString, long assetId, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));
            if (assetId <= 0)
                throw new ArgumentOutOfRangeException(nameof(assetId));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"update assets set sales = coalesce(sales, 0) + 1 where asset_id = @asset_id;";

            using var cmd = new NpgsqlCommand(sql, conn);
            cmd.Parameters.AddWithValue("asset_id", assetId);

            await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Gets the asset IDs and names of featured items (featured_rank > 0), ordered by rank.
        /// </summary>
        public async Task<List<(long AssetId, string Name, int Rank)>> GetFeaturedAssetsAsync(string connectionString, CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrWhiteSpace(connectionString))
                throw new ArgumentException("connectionString is required", nameof(connectionString));

            using var conn = new NpgsqlConnection(connectionString);
            await conn.OpenAsync(cancellationToken).ConfigureAwait(false);

            const string sql = @"select asset_id, name, featured_rank
from assets
where featured_rank > 0
order by featured_rank asc;";

            using var cmd = new NpgsqlCommand(sql, conn);
            using var reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);

            var results = new List<(long, string, int)>();
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                results.Add((
                    reader.GetInt64(0),
                    reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                    reader.GetInt32(2)
                ));
            }

            return results;
        }
    }
}
