using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using Assets;
using Games;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Thumbnails;
using Users;
using Website.Services;
using Webserver.Common;

namespace RobloxWebserver.Controllers
{
    /// <summary>
    /// Represents media (image or video) for a place
    /// </summary>
    public class PlaceMedia
    {
        public string Type { get; set; } = "image"; // "image" or "video"
        public string Url { get; set; } = string.Empty;
        public string? ThumbnailUrl { get; set; } // For videos
        public bool IsVideo { get; set; } = false;
        public bool IsAutoGenerated { get; set; } = false;
    }

    /// <summary>
    /// Minimal endpoints backing game/universe creation from the legacy /develop page.
    /// This currently creates a universe and a single root place asset, then redirects
    /// to a placeholder configure page for that universe.
    /// </summary>
    [ApiController]
    [Route("games")]
    [Authorize]
    public sealed class GamesController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IThumbnailService _thumbnailService;
        private readonly GamesCacheService _cacheService;
        private readonly ILogger<GamesController> _logger;

        public GamesController(
            IConfiguration configuration, 
            IThumbnailService thumbnailService,
            GamesCacheService cacheService,
            ILogger<GamesController> logger)
        {
            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            _thumbnailService = thumbnailService ?? throw new ArgumentNullException(nameof(thumbnailService));
            _cacheService = cacheService ?? throw new ArgumentNullException(nameof(cacheService));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Handles the "Create New Game" button from /develop. For now this immediately creates
        /// a universe and root place row in the database and then redirects user to a
        /// not-yet-implemented universe configuration page.
        /// </summary>
        [HttpGet("create")]
        public async Task<IActionResult> Create(CancellationToken cancellationToken)
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            if (string.IsNullOrWhiteSpace(userIdClaim) || !long.TryParse(userIdClaim, out var userId) || userId <= 0)
            {
                return Redirect("/");
            }

            var connStr = _configuration.GetConnectionString("Default");
            var assetsRoot = _configuration["Assets:Directory"];
            var starterPlacePath = _configuration["Games:StarterPlacePath"];
            var enableCooldownRaw = _configuration["Games:EnableCreationCooldown"];
            var enableCooldown = true;
            if (!string.IsNullOrWhiteSpace(enableCooldownRaw) && bool.TryParse(enableCooldownRaw, out var parsedCooldown))
            {
                enableCooldown = parsedCooldown;
            }
            UniverseInfo universe;
            try
            {
                var creatorUserName = await UserQueries.GetUserNameByIdAsync(connStr, userId, cancellationToken)
                    .ConfigureAwait(false) ?? User.Identity?.Name ?? string.Empty;

                universe = await GameCreationService.CreateUniverseWithRootPlaceAsync(
                    connStr,
                    userId,
                    creatorUserName,
                    assetsRoot,
                    starterPlacePath,
                    enableCooldown,
                    _thumbnailService,
                    _configuration,
                    cancellationToken);
            }
            catch
            {
                // If anything fails, fall back to the develop page for now.
                return Redirect("/develop?Page=universes");
            }

            // In real Roblox this would go to /universes/configure?id={universeId}.
            // That endpoint does not exist yet in this clone, so we redirect back
            // to the universes view where the new row can eventually appear once
            // listing is wired up.
            return Redirect("/develop?Page=universes");
        }

        /// <summary>
        /// Returns HTML game cards for the games page. This endpoint is called via AJAX
        /// to load more games dynamically as users scroll or interact with filters.
        /// </summary>
        [HttpGet("moreresultscached")]
        [AllowAnonymous]
        public async Task<IActionResult> MoreResultsCached(
            int SortFilter = 1,
            int TimeFilter = 0,
            int RegionFilter = 183,
            int GenreID = 0,
            int GameFilter = 1,
            int MinBCLevel = 0,
            int StartRows = 0,
            int MaxRows = 14,
            bool IsUserLoggedIn = false,
            int NumberOfRowsToOccupy = 1,
            int NumberOfColumns = 4,
            bool IsInHorizontalScrollMode = false,
            int DeviceTypeId = 1,
            int AdSpan = 0,
            int AdAlignment = 0,
            int v = 2,
            int PersonalizedUniverseId = 0,
            bool useFakeResults = false,
            bool IsGamesThumbnailAsyncEnabled = false,
            CancellationToken cancellationToken = default)
        {
            try
            {
                var connStr = _configuration.GetConnectionString("Default");
                List<GamesQueries.GameEntry> games = new List<GamesQueries.GameEntry>();


                const int maxGamesLimit = 64;
                if (StartRows >= maxGamesLimit)
                {
                    return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
                }

                var adjustedMaxRows = Math.Min(MaxRows, maxGamesLimit - StartRows);
                if (adjustedMaxRows <= 0)
                {
                    return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
                }

                bool useCache = await _cacheService.IsCacheAvailableAsync(SortFilter, GenreID, cancellationToken);
                
                if (useCache)
                {
                    var cachedGames = await _cacheService.GetCachedGamesAsync(
                        SortFilter, GenreID, StartRows, adjustedMaxRows, cancellationToken);
                    
                    if (cachedGames.Count > 0)
                    {
                        games = GamesCacheService.ToGameEntries(cachedGames);
                    }
                    else
                    {
                        useCache = false;
                    }
                }
                
                if (!useCache)
                {
                    if (GameFilter == 0 && IsUserLoggedIn)
                    {
                        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                        if (string.IsNullOrWhiteSpace(userIdClaim) || !long.TryParse(userIdClaim, out var userId))
                        {
                            return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
                        }

                        games = await GamesQueries.GetUserPublicGamesAsync(
                            userId, SortFilter, StartRows, adjustedMaxRows, GenreID, connStr, cancellationToken);
                    }
                    else
                    {
                        games = await GamesQueries.GetPublicGamesAsync(
                            SortFilter, TimeFilter, GenreID, RegionFilter, 
                            StartRows, adjustedMaxRows, connStr, cancellationToken);
                    }
                }

                var html = BuildGamesHtml(games, StartRows);
                return Content(html, "text/html");
            }
            catch (Exception ex)
            {
                // Log error and return empty result
                Console.WriteLine($"Error loading games: {ex.Message}");
                return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
            }
        }

        private string BuildGamesHtml(List<GamesQueries.GameEntry> games, int startRow)
        {
            var html = "<div class=\"hidden-item hidden\" id=keyword></div>";

            foreach (var game in games)
            {
                var position = startRow + games.IndexOf(game);
                var gameNameSlug = System.Text.RegularExpressions.Regex.Replace(game.Name.ToLower(), @"[^a-z0-9\s-]", "").Trim();
                gameNameSlug = System.Text.RegularExpressions.Regex.Replace(gameNameSlug, @"\s+", "-");
                html += $@"
<li class=""list-item game-card"">
    <div class=game-card-container>
        <a href=""/games/{game.PlaceId}/{gameNameSlug}"" class=game-card-link>
            <div class=game-card-thumb-container>
                <img class=game-card-thumb src={game.IconUrl} alt=""{game.Name}"" thumbnail=""{{&#34;Final&#34;:true,&#34;Url&#34;:&#34;{game.IconUrl}&#34;,&#34;RetryUrl&#34;:null,&#34;UserId&#34;:0,&#34;EndpointType&#34;:&#34;Avatar&#34;}}"" image-retry>
            </div>
            <div class=""text-overflow game-card-name"" title=""{game.Name}"" ng-non-bindable>{game.Name}</div>
            <div class=game-card-name-secondary>{game.Playing} Playing</div>
            <div class=game-card-vote>
                <div class=vote-bar data-voting-processed=false>
                    <div class=vote-thumbs-up>
                        <span class=icon-like-gray-16x16></span>
                    </div>
                    <div class=vote-container data-upvotes={game.UpVotes} data-downvotes={game.DownVotes}>
                        <div id=vote-background class=vote-background></div>
                        <div class=vote-percentage></div>
                        <div class=vote-mask>
                            <div class=""segment seg-1""></div>
                            <div class=""segment seg-2""></div>
                            <div class=""segment seg-3""></div>
                            <div class=""segment seg-4""></div>
                        </div>
                    </div>
                    <div class=vote-thumbs-down>
                        <span class=icon-dislike-gray-16x16></span>
                    </div>
                </div>
                <div class=vote-counts>
                    <div id=vote-down-count class=vote-down-count>{game.DownVotes:N0}</div>
                    <div id=vote-up-count class=vote-up-count>{game.UpVotes:N0}</div>
                </div>
            </div>
        </a>
        <div class=game-card-footer>
            <div class=creator>
                <span class=""text-label xsmall text-overflow""> By <a class=text-link href=""/users/{game.CreatorUserId}/profile"" ng-non-bindable>{game.CreatorName}</a> </span>
            </div>
        </div>
    </div>
</li>";
            }

            return html;
        }

        /// <summary>
    /// Advanced search endpoint for game search functionality with enhanced features
    /// </summary>
    [HttpGet("advancedsearch")]
    [AllowAnonymous]
    public async Task<IActionResult> AdvancedSearch(
    string keyword = "",
    int startRow = 0,
    int maxRows = 40,
    CancellationToken cancellationToken = default)
{
    try
    {
        var connStr = _configuration.GetConnectionString("Default");
        List<GamesQueries.GameEntry> games;

        if (string.IsNullOrWhiteSpace(keyword))
        {
            return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
        }

        games = await GamesQueries.SearchGamesAdvancedAsync(
            keyword, startRow, maxRows, connStr, cancellationToken);

        var html = BuildGamesHtml(games, startRow);

        return Content(html, "text/html");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Error in advanced search: {ex.Message}");
        return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
    }
}

        /// <summary>
        /// Search endpoint for game search functionality
        /// </summary>
        [HttpGet("moreresultsuncached")]
        [AllowAnonymous]
        public async Task<IActionResult> MoreResultsUncached(
            int StartRows = 0,
            int MaxRows = 40,
            bool IsUserLoggedIn = false,
            int NumberOfColumns = 4,
            bool IsInHorizontalScrollMode = false,
            int DeviceTypeId = 1,
            int AdSpan = 0,
            int AdAlignment = 0,
            int v = 2,
            string Keyword = "",
            bool IsSecure = false,
            bool UseFakeResults = false,
            string SuggestedCorrection = "",
            string SuggestionKeyword = "",
            string SuggestionReplacedKeyword = "",
            bool IsGamesThumbnailAsyncEnabled = false,
            CancellationToken cancellationToken = default)
        {
            try
            {
                var connStr = _configuration.GetConnectionString("Default");
                List<GamesQueries.GameEntry> games;

                if (string.IsNullOrWhiteSpace(Keyword))
                {
                    return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
                }

                games = await GamesQueries.SearchPublicGamesAsync(
                    Keyword, StartRows, MaxRows, connStr, cancellationToken);

                var html = BuildGamesHtml(games, StartRows);

                return Content(html, "text/html");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error searching games: {ex.Message}");
                return Content("<div class=\"hidden-item hidden\" id=keyword></div>", "text/html");
            }
        }

        /// <summary>
        /// Get place media for thumbnail carousel (prioritizes custom thumbnails, falls back to auto-generated)
        /// </summary>
        private async Task<List<PlaceMedia>> GetPlaceMediaAsync(long rootPlaceId, string connectionString, CancellationToken cancellationToken = default)
        {
            var media = new List<PlaceMedia>();
            var customThumbnails = await Thumbnails.PlaceThumbnail.GetPlaceThumbnailsAsync(connectionString, rootPlaceId, cancellationToken);
            
            foreach (var thumbnail in customThumbnails)
            {
                var thumbnailType = thumbnail.GetType().GetProperty("type")?.GetValue(thumbnail)?.ToString();
                var url = thumbnail.GetType().GetProperty("url")?.GetValue(thumbnail)?.ToString();
                var videoUrl = thumbnail.GetType().GetProperty("videoUrl")?.GetValue(thumbnail)?.ToString();
                
                if (thumbnailType == "image" && !string.IsNullOrWhiteSpace(url))
                {
                    media.Add(new PlaceMedia
                    {
                        Type = "image",
                        Url = url,
                        IsVideo = false
                    });
                }
                else if (thumbnailType == "video" && !string.IsNullOrWhiteSpace(videoUrl))
                {
                    var thumbnailUrl = "";
                    
                    if (YouTubeUtilities.IsYouTubeUrl(videoUrl))
                    {
                        var videoId = YouTubeUtilities.ExtractVideoId(videoUrl);
                        if (!string.IsNullOrWhiteSpace(videoId))
                        {
                            thumbnailUrl = YouTubeUtilities.GetThumbnailUrl(videoId);
                        }
                    }
                    
                    media.Add(new PlaceMedia
                    {
                        Type = "video",
                        Url = videoUrl,
                        ThumbnailUrl = thumbnailUrl,
                        IsVideo = true
                    });
                }
            }
            
            if (media.Count == 0)
            {
                var assetRepo = new AssetMetadataRepository();
                var placeAsset = await assetRepo.GetPlaceByIdAsync(connectionString, rootPlaceId, cancellationToken);
                
                if (placeAsset != null)
                {
                    if (!string.IsNullOrWhiteSpace(placeAsset.PlaceGeneratedThumbnailUrl))
                    {
                        media.Add(new PlaceMedia
                        {
                            Type = "image",
                            Url = placeAsset.PlaceGeneratedThumbnailUrl,
                            IsVideo = false,
                            IsAutoGenerated = true
                        });
                    }
                    
                    if (placeAsset.PlaceVideoThumbnail && !string.IsNullOrWhiteSpace(placeAsset.PlaceThumbnailVideo))
                    {
                        var videoUrl = placeAsset.PlaceThumbnailVideo;
                        var thumbnailUrl = "";

                        if (YouTubeUtilities.IsYouTubeUrl(videoUrl))
                        {
                            var videoId = YouTubeUtilities.ExtractVideoId(videoUrl);
                            if (!string.IsNullOrWhiteSpace(videoId))
                            {
                                thumbnailUrl = YouTubeUtilities.GetThumbnailUrl(videoId);
                            }
                        }
                        
                        media.Add(new PlaceMedia
                        {
                            Type = "video",
                            Url = videoUrl,
                            ThumbnailUrl = thumbnailUrl,
                            IsVideo = true
                        });
                    }
                }
            }

            if (media.Count == 0)
            {
                media.Add(new PlaceMedia
                {
                    Type = "image",
                    Url = "/images/DefaultPlaceIcon.png",
                    IsVideo = false
                });
            }

            return media;
        }

        /// <summary>
        /// Returns the universe name page for a specific game/place
        /// </summary>
        [HttpGet("{id}/{name}")]
        [AllowAnonymous]
        public async Task<IActionResult> GetGameName(long id, string name, CancellationToken cancellationToken = default)
        {
            try
            {
                var connStr = _configuration.GetConnectionString("Default");
                var universeId = await GamesRepository.GetUniverseIdFromPlaceIdAsync(connStr, id, cancellationToken);
                if (!universeId.HasValue)
                {
                    return NotFound();
                }

                var universe = await GamesRepository.GetUniverseAsync(connStr, universeId.Value, cancellationToken);
                if (universe == null)
                {
                    return NotFound();
                }

                var description = await GamesRepository.GetPlaceDescriptionAsync(connStr, universe.RootPlaceId, cancellationToken);
                var placeThumbnails = await Thumbnails.PlaceThumbnail.GetPlaceThumbnailsAsync(connStr, universe.RootPlaceId, cancellationToken);
                var assetRepo = new AssetMetadataRepository();
                var placeAsset = await assetRepo.GetPlaceByIdAsync(connStr, universe.RootPlaceId, cancellationToken);
                var videoUrl = placeAsset?.PlaceVideoThumbnail == true ? placeAsset.PlaceThumbnailVideo : null;
                var autoGeneratedThumbnailUrl = placeAsset?.PlaceGeneratedThumbnailUrl;
                var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                long userId = 0;
                var isUserAuthenticated = !string.IsNullOrWhiteSpace(userIdClaim) && long.TryParse(userIdClaim, out userId) && userId > 0;
                bool isUserFavorite = false;
                int favoriteCount = 0;
                var assetsRepo = new Assets.AssetsRepository();
                
                if (isUserAuthenticated)
                {
                    isUserFavorite = await assetsRepo.UserHasFavoritedAsync(connStr, userId, id, cancellationToken);
                }
                
                favoriteCount = await assetsRepo.GetFavoriteCountAsync(connStr, id, cancellationToken);
                var creatorUserName = await UserQueries.GetUserNameByIdAsync(connStr, universe.CreatorUserId, cancellationToken)
                    .ConfigureAwait(false) ?? "Unknown";

                var votingService = new Games.VotingService(connStr);
                var (upVotes, downVotes) = await votingService.GetAssetVotesAsync(id, cancellationToken);
                bool? userVote = null;
                if (isUserAuthenticated)
                {
                    userVote = await votingService.GetUserVoteAsync(userId, id, cancellationToken);
                }

                var recommendedGames = await GamesQueries.GetRecommendedGamesAsync(7, connStr, cancellationToken);

                ViewBag.RecommendedGames = recommendedGames.Select(game => new
                {
                    PlaceId = game.PlaceId,
                    Name = game.Name,
                    CreatorName = game.CreatorName,
                    CreatorId = game.CreatorUserId,
                    PlayingCount = game.Playing,
                    ThumbnailUrl = game.IconUrl,
                    VoteUpCount = game.UpVotes,
                    VoteDownCount = game.DownVotes
                }).Cast<dynamic>().ToList();

                ViewBag.Id = id;
                ViewBag.Name = universe.Name;
                ViewBag.Description = description ?? string.Empty;
                ViewBag.CreatorUserId = universe.CreatorUserId;
                ViewBag.CreatorUserName = creatorUserName;
                ViewBag.UpVotes = upVotes;
                ViewBag.DownVotes = downVotes;
                ViewBag.UserVote = userVote;
                ViewBag.FavoriteCount = favoriteCount;
                ViewBag.IsUserAuthenticated = isUserAuthenticated;
                ViewBag.IsUserFavorite = isUserFavorite;
                ViewBag.PlaceThumbnails = placeThumbnails;
                ViewBag.VideoUrl = videoUrl;
                ViewBag.AutoGeneratedThumbnailUrl = autoGeneratedThumbnailUrl;
                
                var placeAdditionalData = await Assets.AssetsRepository.GetPlaceAdditionalDataAsync(connStr, universe.RootPlaceId, cancellationToken);
                if (placeAdditionalData.HasValue)
                {
                    ViewBag.CreatedAt = placeAdditionalData.Value.CreatedAt;
                    ViewBag.UpdatedAt = placeAdditionalData.Value.UpdatedAt;
                    ViewBag.MaxPlayers = placeAdditionalData.Value.MaxPlayers;
                    ViewBag.Genre = placeAdditionalData.Value.Genre;
                    ViewBag.IsAllGenresAllowed = placeAdditionalData.Value.IsAllGenresAllowed;
                    ViewBag.AllowedGearTypes = placeAdditionalData.Value.AllowedGearTypes;
                    ViewBag.PrivateServersAllowed = placeAdditionalData.Value.PrivateServersAllowed;
                    ViewBag.PrivateServersFree = placeAdditionalData.Value.PrivateServersFree;
                    ViewBag.PrivateServersPrice = placeAdditionalData.Value.PrivateServersPrice;
                }

                ViewBag.IsCopylocked = !(placeAsset?.IsCopyingAllowed ?? false);

                return View("~/Views/Pages/games/{id}/UniverseName.cshtml");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error loading game name for place ID {PlaceId}", id);
                return StatusCode(500);
            }
        }

        /// <summary>
        /// Returns the voting HTML for a specific game/place (AJAX endpoint for LoadVotingService)
        /// </summary>
        [HttpGet("votingservice/{id}")]
        [AllowAnonymous]
        public async Task<IActionResult> GetVotingService(long id, CancellationToken cancellationToken = default)
        {
            try
            {
                var connStr = _configuration.GetConnectionString("Default");
                var universeId = await GamesRepository.GetUniverseIdFromPlaceIdAsync(connStr, id, cancellationToken);
                if (!universeId.HasValue)
                {
                    return NotFound();
                }

                var universe = await GamesRepository.GetUniverseAsync(connStr, universeId.Value, cancellationToken);
                if (universe == null)
                {
                    return NotFound();
                }

                var votingService = new Games.VotingService(connStr);
                var (upVotes, downVotes) = await votingService.GetAssetVotesAsync(id, cancellationToken);
                bool? userVote = null;
                var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
                long userId = 0;
                bool isUserAuthenticated = userIdClaim != null && long.TryParse(userIdClaim.Value, out userId) && userId > 0;
                
                if (isUserAuthenticated)
                {
                    userVote = await votingService.GetUserVoteAsync(userId, id, cancellationToken);
                }

                var encodedUniverseName = System.Net.WebUtility.UrlEncode(universe.Name);
                var votingHtml = $@"
<li id=""voting-section"" class=""voting-panel body"" data-target-id=""{id}"" data-total-up-votes=""{upVotes}"" data-total-down-votes=""{downVotes}"" data-vote-modal=""PlayGame"" data-user-authenticated=""{isUserAuthenticated.ToString().ToLower()}"" data-vote-url="""">
    <div class=""loading"" style=""display:none""></div>
    <div class=""vote-summary"">
        <div class=""voting-details"">
            <div class=""users-vote {(userVote != null ? "has-voted" : "")}"">
                <div class=""upvote {(userVote == true ? "selected checked" : "")}""><span class=""icon-like {(userVote == true ? "selected checked" : "")}""></span></div>
                <div class=""vote-details"">
                    <div class=""vote-container"">
                        <div class=""vote-background""></div>
                        <div class=""vote-percentage""></div>
                        <div class=""vote-mask"">
                            <div class=""segment seg-1""></div>
                            <div class=""segment seg-2""></div>
                            <div class=""segment seg-3""></div>
                            <div class=""segment seg-4""></div>
                        </div>
                    </div>
                    <div class=""vote-numbers"">
                        <div class=""count-left""><span id=""vote-up-text"" title=""{upVotes}"" class=""vote-text total-upvotes-text"">{upVotes}</span></div>
                        <div class=""count-right""><span id=""vote-down-text"" title=""{downVotes}"" class=""vote-text total-downvotes-text"">{downVotes}</span></div>
                    </div>
                </div>
                <div class=""downvote {(userVote == false ? "selected checked" : "")}""><span class=""icon-dislike {(userVote == false ? "selected checked" : "")}""></span></div>
            </div>
        </div>
    </div>
</li>
<script>
    Roblox.Voting.Resources = {{
        emailVerifiedTitle: ""Verify Your Email"",
        emailVerifiedMessage: ""You must verify your email before you can vote. You can verify your email on the <a href='/my/account?confirmemail=1'>Account</a> page."",
        playGameTitle: ""Play Game"",
        playGameMessage: ""You must play the game before you can vote on it."",
        useModelTitle: ""Use Model"",
        useModelMessage: ""You must use this model before you can vote on it."",
        installPluginTitle: ""Install Plugin"",
        installPluginMessage: ""You must install this plugin before you can vote on it."",
        buyGamePassTitle: ""Buy Game Pass"",
        buyGamePassMessage: ""You must own this game pass before you can vote on it."",
        floodCheckThresholdMetTitle: ""Slow Down"",
        floodCheckThresholdMetMessage: ""You're voting too quickly. Come back later and try again."",
        unknownProblemTitle: ""Something Broke"",
        unknownProblemMessage: ""There was an unknown problem voting. Please try again."",
        guestUserTitle: ""Login to Vote"",
        guestUserMessage: ""<div>You must login to vote.</div> <div>Please <a href='/newlogin?returnUrl=%2Fgames%2F{id}%2F{encodedUniverseName}'>login or register</a> to continue.</div>"",
        returnUrl: '/newlogin?returnUrl=%2Fgames%2F{id}%2F{encodedUniverseName}',
        accountUnderOneDayTitle: ""Voter Feedback"",
        accountUnderOneDayMessage: ""You will be able to vote on Games and Studio Models later, after you've had a chance to experience ROBLOX a bit more. Come back to this couple days."",
        assetNotVoteableTitle: ""Unable to Vote"",
        assetNotVoteableMessage: ""This asset may not be voted on at this time."",
        accept: ""Verify"",
        decline: ""Cancel"",
        login: ""Login"",
        ok: ""OK""
    }};
    Roblox.Voting.Initialize();
</script>";

                return Content(votingHtml, "text/html");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error loading voting service for place ID {PlaceId}", id);
                return StatusCode(500);
            }
        }

        private string GenerateRandomString(int length)
        {
            return Common.StringUtilities.GenerateRandomString(length);
        }
    }
}